--Krawler Plexus
--Omega references: Ghostrick Festival (c35871958), Krawler Glial (c51205763)
local s,id=GetID(); local SET_KRAWLER=0x104; local MSG_ID=133669838
function s.initial_effect(c)
 local e0=aux.AddLinkProcedure(c,function(x) return x:IsLinkSetCard(SET_KRAWLER) end,1,1); e0:SetProperty(e0:GetProperty()|EFFECT_FLAG_SET_AVAILABLE); c:EnableReviveLimit(); c:SetSPSummonOnce(id)
 local e1=Effect.CreateEffect(c); e1:SetDescription(aux.Stringid(MSG_ID,0)); e1:SetCategory(CATEGORY_SPECIAL_SUMMON+CATEGORY_POSITION); e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O); e1:SetCode(EVENT_SPSUMMON_SUCCESS); e1:SetProperty(EFFECT_FLAG_DELAY); e1:SetCountLimit(1,id); e1:SetCost(s.dcost); e1:SetTarget(s.sptg); e1:SetOperation(s.spop); c:RegisterEffect(e1)
 local e2=Effect.CreateEffect(c); e2:SetDescription(aux.Stringid(MSG_ID,1)); e2:SetCategory(CATEGORY_TODECK+CATEGORY_ATKCHANGE); e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O); e2:SetCode(EVENT_LEAVE_FIELD); e2:SetRange(LOCATION_GRAVE); e2:SetProperty(EFFECT_FLAG_DELAY); e2:SetCondition(s.lvcon); e2:SetTarget(s.tdtg); e2:SetOperation(s.tdop); c:RegisterEffect(e2)
end
function s.dcost(e,tp,eg,ep,ev,re,r,rp,chk) if chk==0 then return true end local yes=Duel.IsExistingMatchingCard(Card.IsDiscardable,tp,LOCATION_HAND,0,1,nil) and Duel.SelectYesNo(tp,aux.Stringid(MSG_ID,2)); e:SetLabel(yes and 1 or 0); if yes then Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_DISCARD); local g=Duel.SelectMatchingCard(tp,Card.IsDiscardable,tp,LOCATION_HAND,0,1,1,nil); Duel.SendtoGrave(g,REASON_COST+REASON_DISCARD) end end
function s.spf(c,e,tp) return c:IsSetCard(SET_KRAWLER) and c:IsCanBeSpecialSummoned(e,0,tp,false,false,POS_FACEDOWN_DEFENSE) end
function s.sptg(e,tp,eg,ep,ev,re,r,rp,chk) if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0 and Duel.IsExistingMatchingCard(aux.NecroValleyFilter(s.spf),tp,LOCATION_GRAVE+LOCATION_REMOVED,0,1,nil,e,tp) end Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_GRAVE+LOCATION_REMOVED) end
function s.spop(e,tp) if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SPSUMMON); local g=Duel.SelectMatchingCard(tp,aux.NecroValleyFilter(s.spf),tp,LOCATION_GRAVE+LOCATION_REMOVED,0,1,1,nil,e,tp); if Duel.SpecialSummon(g,0,tp,tp,false,false,POS_FACEDOWN_DEFENSE)>0 then Duel.ConfirmCards(1-tp,g); if e:GetLabel()==1 and Duel.IsExistingMatchingCard(Card.IsFacedown,tp,LOCATION_MZONE,0,1,nil) and Duel.SelectYesNo(tp,aux.Stringid(MSG_ID,3)) then Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_POSCHANGE); local tc=Duel.SelectMatchingCard(tp,Card.IsFacedown,tp,LOCATION_MZONE,0,1,1,nil):GetFirst(); Duel.ChangePosition(tc,POS_FACEUP_DEFENSE) end end end
function s.lvcon(e,tp,eg,ep,ev,re,r,rp) return eg:IsExists(function(c,tp) return c:IsPreviousControler(tp) and c:IsPreviousLocation(LOCATION_MZONE) and c:IsSetCard(SET_KRAWLER) and c:IsReason(REASON_EFFECT) and c:GetReasonPlayer()==1-tp end,1,nil,tp) end
function s.tdf(c) return c:IsSetCard(SET_KRAWLER) and c:IsType(TYPE_MONSTER) and c:IsAbleToDeck() end
function s.tdtg(e,tp,eg,ep,ev,re,r,rp,chk) local c=e:GetHandler(); if chk==0 then return c:IsAbleToDeck() and Duel.IsExistingMatchingCard(s.tdf,tp,LOCATION_GRAVE,0,2,c) end Duel.SetOperationInfo(0,CATEGORY_TODECK,nil,3,tp,LOCATION_GRAVE) end
function s.tdop(e,tp) local c=e:GetHandler(); if not c:IsRelateToEffect(e) or not c:IsAbleToDeck() then return end Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TODECK); local g=Duel.SelectMatchingCard(tp,s.tdf,tp,LOCATION_GRAVE,0,2,2,c); g:AddCard(c); if Duel.SendtoDeck(g,nil,SEQ_DECKSHUFFLE,REASON_EFFECT)==3 then local ex=Effect.CreateEffect(c); ex:SetType(EFFECT_TYPE_FIELD); ex:SetCode(EFFECT_UPDATE_ATTACK); ex:SetTargetRange(LOCATION_MZONE,0); ex:SetTarget(function(e,c) return c:IsSetCard(SET_KRAWLER) end); ex:SetValue(300); ex:SetReset(RESET_PHASE+PHASE_END); Duel.RegisterEffect(ex,tp); local ex2=ex:Clone(); ex2:SetCode(EFFECT_UPDATE_DEFENSE); Duel.RegisterEffect(ex2,tp) end end
