namespace System.Data;

[DefaultProperty("ConstraintName")]
[TypeConverter(typeof(ConstraintConverter))]
public abstract class Constraint
{
	private string _schemaName; //Field offset: 0x10
	private bool _inCollection; //Field offset: 0x18
	private DataSet _dataSet; //Field offset: 0x20
	internal string _name; //Field offset: 0x28
	internal PropertyCollection _extendedProperties; //Field offset: 0x30

	[CLSCompliant(False)]
	protected override DataSet _DataSet
	{
		[CallerCount(Count = 12)]
		[DeduplicatedMethod]
		 get { } //Length: 5
	}

	[DefaultValue(null)]
	public override string ConstraintName
	{
		[CallerCount(Count = 15)]
		[DeduplicatedMethod]
		 get { } //Length: 5
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(CultureInfo), Member = "get_CurrentCulture", ReturnType = typeof(CultureInfo))]
		[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool), typeof(CultureInfo)}, ReturnType = typeof(int))]
		[Calls(Type = typeof(ConstraintCollection), Member = "RegisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(ConstraintCollection), Member = "UnregisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(ExceptionBuilder), Member = "NoConstraintName", ReturnType = typeof(Exception))]
		[CallsDeduplicatedMethods(Count = 8)]
		[CallsUnknownMethods(Count = 4)]
		 set { } //Length: 521
	}

	[Browsable(False)]
	public PropertyCollection ExtendedProperties
	{
		[CalledBy(Type = typeof(DataTable), Member = "SerializeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext), typeof(int), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(DataTable), Member = "CloneTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(DataSet), typeof(bool)}, ReturnType = typeof(DataTable))]
		[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
		[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(ForeignKeyConstraint))]
		[CalledBy(Type = typeof(Merger), Member = "MergeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
		[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(UniqueConstraint))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint)}, ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ForeignKeyConstraint), typeof(bool)}, ReturnType = typeof(bool))]
		[CallerCount(Count = 21)]
		[Calls(Type = typeof(PropertyCollection), Member = ".ctor", ReturnType = typeof(void))]
		[CallsUnknownMethods(Count = 1)]
		 get { } //Length: 106
	}

	internal override bool InCollection
	{
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
		[CalledBy(Type = typeof(UniqueConstraint), Member = "set_InCollection", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CallerCount(Count = 1)]
		[CallsDeduplicatedMethods(Count = 1)]
		[CallsUnknownMethods(Count = 3)]
		internal set { } //Length: 84
	}

	internal string SchemaName
	{
		[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
		[CallerCount(Count = 6)]
		[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
		[CallsDeduplicatedMethods(Count = 1)]
		internal get { } //Length: 59
		[CalledBy(Type = typeof(XmlTreeGen), Member = "GenerateConstraintNames", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(bool)}, ReturnType = typeof(void))]
		[CallerCount(Count = 1)]
		[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
		[CallsUnknownMethods(Count = 1)]
		internal set { } //Length: 57
	}

	public abstract DataTable Table
	{
		 get { } //Length: 0
	}

	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(String[]), typeof(String[]), typeof(AcceptRejectRule), typeof(Rule), typeof(Rule)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(ForeignKeyConstraint))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(String[]), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(UniqueConstraint))]
	[CallerCount(Count = 12)]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 2)]
	protected Constraint() { }

	internal abstract bool CanBeRemovedFromCollection(ConstraintCollection constraint, bool fThrowException) { }

	internal abstract bool CanEnableConstraint() { }

	internal abstract void CheckCanAddToCollection(ConstraintCollection constraint) { }

	internal abstract void CheckConstraint(DataRow row, DataRowAction action) { }

	[CalledBy(Type = typeof(DataTable), Member = "SetCaseSensitiveValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool), typeof(bool), typeof(bool)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(DataTable), Member = "SetLocaleValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CultureInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ConstraintViolation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 3)]
	internal void CheckConstraint() { }

	internal abstract void CheckState() { }

	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_ChildKey", ReturnType = typeof(DataKey))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "CanBeRemovedFromCollection", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ConstraintCollection), typeof(bool)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_UpdateRule", ReturnType = typeof(Rule))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_RelatedTable", ReturnType = typeof(DataTable))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_ParentKey", ReturnType = typeof(DataKey))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_RelatedColumnsReference", ReturnType = typeof(DataColumn[]))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_RelatedColumns", ReturnType = typeof(DataColumn[]))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_DeleteRule", ReturnType = typeof(Rule))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Equals", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_AcceptRejectRule", ReturnType = typeof(AcceptRejectRule))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "CheckConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRow), typeof(DataRowAction)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "CheckCanRemoveParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRow)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_Table", ReturnType = typeof(DataTable))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "get_Columns", ReturnType = typeof(DataColumn[]))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(ForeignKeyConstraint))]
	[CallerCount(Count = 21)]
	[Calls(Type = typeof(ExceptionBuilder), Member = "BadObjectPropertyAccess", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 4)]
	protected void CheckStateForProperty() { }

	internal abstract Constraint Clone(DataSet destination, bool ignoreNSforTableLookup) { }

	internal abstract Constraint Clone(DataSet destination) { }

	internal abstract bool ContainsColumn(DataColumn column) { }

	[CallerCount(Count = 12)]
	[DeduplicatedMethod]
	protected override DataSet get__DataSet() { }

	[CallerCount(Count = 15)]
	[DeduplicatedMethod]
	public override string get_ConstraintName() { }

	[CalledBy(Type = typeof(DataTable), Member = "SerializeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext), typeof(int), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataTable), Member = "CloneTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(DataSet), typeof(bool)}, ReturnType = typeof(DataTable))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(ForeignKeyConstraint))]
	[CalledBy(Type = typeof(Merger), Member = "MergeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(UniqueConstraint))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ForeignKeyConstraint), typeof(bool)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 21)]
	[Calls(Type = typeof(PropertyCollection), Member = ".ctor", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 1)]
	public PropertyCollection get_ExtendedProperties() { }

	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	internal override bool get_InCollection() { }

	[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
	[CallerCount(Count = 6)]
	[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[CallsDeduplicatedMethods(Count = 1)]
	internal string get_SchemaName() { }

	public abstract DataTable get_Table() { }

	internal abstract bool IsConstraintViolated() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CultureInfo), Member = "get_CurrentCulture", ReturnType = typeof(CultureInfo))]
	[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool), typeof(CultureInfo)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(ConstraintCollection), Member = "RegisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ConstraintCollection), Member = "UnregisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "NoConstraintName", ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 8)]
	[CallsUnknownMethods(Count = 4)]
	public override void set_ConstraintName(string value) { }

	[CalledBy(Type = typeof(UniqueConstraint), Member = "set_InCollection", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 3)]
	internal override void set_InCollection(bool value) { }

	[CalledBy(Type = typeof(XmlTreeGen), Member = "GenerateConstraintNames", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[CallsUnknownMethods(Count = 1)]
	internal void set_SchemaName(string value) { }

	[CallerCount(Count = 51)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	public virtual string ToString() { }

}

