namespace System.Data;

[DefaultProperty("RelationName")]
[TypeConverter(typeof(RelationshipConverter))]
public class DataRelation
{
	private static int s_objectTypeCount; //Field offset: 0x0
	private DataSet _dataSet; //Field offset: 0x10
	internal PropertyCollection _extendedProperties; //Field offset: 0x18
	internal string _relationName; //Field offset: 0x20
	private DataKey _childKey; //Field offset: 0x28
	private DataKey _parentKey; //Field offset: 0x30
	private UniqueConstraint _parentKeyConstraint; //Field offset: 0x38
	private ForeignKeyConstraint _childKeyConstraint; //Field offset: 0x40
	internal String[] _parentColumnNames; //Field offset: 0x48
	internal String[] _childColumnNames; //Field offset: 0x50
	internal string _parentTableName; //Field offset: 0x58
	internal string _childTableName; //Field offset: 0x60
	internal string _parentTableNamespace; //Field offset: 0x68
	internal string _childTableNamespace; //Field offset: 0x70
	internal bool _nested; //Field offset: 0x78
	internal bool _createConstraints; //Field offset: 0x79
	private bool _checkMultipleNested; //Field offset: 0x7A
	private readonly int _objectID; //Field offset: 0x7C
	[CompilerGenerated]
	private PropertyChangedEventHandler PropertyChanging; //Field offset: 0x80

	internal bool CheckMultipleNested
	{
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		internal set { } //Length: 4
	}

	internal String[] ChildColumnNames
	{
		[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
		[CallerCount(Count = 2)]
		[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
		internal get { } //Length: 11
	}

	public override DataColumn[] ChildColumns
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
		 get { } //Length: 32
	}

	internal DataColumn[] ChildColumnsReference
	{
		[CallerCount(Count = 20)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[DeduplicatedMethod]
		internal get { } //Length: 26
	}

	internal DataKey ChildKey
	{
		[CallerCount(Count = 20)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[DeduplicatedMethod]
		internal get { } //Length: 26
	}

	public override ForeignKeyConstraint ChildKeyConstraint
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		 get { } //Length: 26
	}

	public override DataTable ChildTable
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[CallsUnknownMethods(Count = 2)]
		 get { } //Length: 61
	}

	[Browsable(False)]
	[DesignerSerializationVisibility(DesignerSerializationVisibility::Hidden (0))]
	public override DataSet DataSet
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		 get { } //Length: 26
	}

	[Browsable(False)]
	public PropertyCollection ExtendedProperties
	{
		[CalledBy(Type = typeof(Merger), Member = "MergeRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ForeignKeyConstraint), typeof(bool)}, ReturnType = typeof(bool))]
		[CallerCount(Count = 5)]
		[Calls(Type = typeof(PropertyCollection), Member = ".ctor", ReturnType = typeof(void))]
		[CallsUnknownMethods(Count = 1)]
		 get { } //Length: 106
	}

	[DefaultValue(False)]
	public override bool Nested
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		 get { } //Length: 26
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(ExceptionBuilder), Member = "TableCantBeNestedInTwoTables", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
		[Calls(Type = typeof(ExceptionBuilder), Member = "InvalidParentNamespaceinNestedRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
		[Calls(Type = typeof(ExceptionBuilder), Member = "DatasetConflictingName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
		[Calls(Type = typeof(ExceptionBuilder), Member = "RelationNestedReadOnly", ReturnType = typeof(Exception))]
		[Calls(Type = typeof(ExceptionBuilder), Member = "ConstraintViolation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
		[Calls(Type = typeof(EventSource), Member = "WriteEvent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(long)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(StringComparison)}, ReturnType = typeof(int))]
		[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool), typeof(CultureInfo)}, ReturnType = typeof(int))]
		[Calls(Type = typeof(DataRow), Member = "CheckForLoops", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataTable), Member = "get_ParentRelations", ReturnType = typeof(DataRelationCollection))]
		[Calls(Type = typeof(DataTable), Member = "get_NestedParentsCount", ReturnType = typeof(int))]
		[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(DataTable), Member = "CacheNestedParent", ReturnType = typeof(void))]
		[Calls(Type = typeof(DataRow), Member = "GetParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation), typeof(DataRowVersion)}, ReturnType = typeof(DataRow))]
		[Calls(Type = typeof(DataRelation), Member = "CheckNestedRelations", ReturnType = typeof(void))]
		[Calls(Type = typeof(DataTable), Member = "set_ElementColumnCount", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0"}, ReturnType = typeof(void))]
		[Calls(Type = typeof(PropertyChangedEventArgs), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataColumnCollection), Member = "RegisterColumnName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataColumnCollection), Member = "UnregisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataRelation), Member = "ValidateMultipleNestedRelations", ReturnType = typeof(void))]
		[Calls(Type = typeof(ConstraintCollection), Member = "FindForeignKeyConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(DataColumn[])}, ReturnType = typeof(ForeignKeyConstraint))]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[Calls(Type = typeof(DataRelation), Member = "CheckNamespaceValidityForNestedRelations", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(DataTable), Member = "get_Namespace", ReturnType = typeof(string))]
		[Calls(Type = typeof(DataTable), Member = "IsNamespaceInherited", ReturnType = typeof(bool))]
		[Calls(Type = typeof(DataCommonEventSource), Member = "EnterScope", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T1", "T2"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T1", "T2"}, ReturnType = typeof(long))]
		[CallsDeduplicatedMethods(Count = 36)]
		[CallsUnknownMethods(Count = 98)]
		 set { } //Length: 3741
	}

	internal int ObjectID
	{
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		internal get { } //Length: 4
	}

	internal String[] ParentColumnNames
	{
		[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
		[CallerCount(Count = 2)]
		[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
		internal get { } //Length: 11
	}

	public override DataColumn[] ParentColumns
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
		 get { } //Length: 32
	}

	internal DataColumn[] ParentColumnsReference
	{
		[CallerCount(Count = 62)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
	}

	internal DataKey ParentKey
	{
		[CalledBy(Type = typeof(DataColumn), Member = "set_DataType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(DataColumn), Member = "IsInRelation", ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(Merger), Member = "MergeRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation), typeof(XmlDocument)}, ReturnType = typeof(XmlElement))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
		[CallerCount(Count = 21)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		internal get { } //Length: 26
	}

	public override UniqueConstraint ParentKeyConstraint
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		 get { } //Length: 26
	}

	public override DataTable ParentTable
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		[CallsUnknownMethods(Count = 2)]
		 get { } //Length: 61
	}

	[DefaultValue(null)]
	public override string RelationName
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
		 get { } //Length: 26
	}

	[CalledBy(Type = typeof(XDRSchema), Member = "InstantiateTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(XmlElement), typeof(XmlElement)}, ReturnType = typeof(DataTable))]
	[CalledBy(Type = typeof(XSDSchema), Member = "InstantiateTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(XmlSchemaElement), typeof(XmlSchemaComplexType), typeof(bool)}, ReturnType = typeof(DataTable))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Interlocked), Member = "Increment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Int32&)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0", "T1", "T2", "T3", "T4"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0", "T1", "T2", "T3", "T4"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRelation), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 11)]
	public DataRelation(string relationName, DataColumn parentColumn, DataColumn childColumn, bool createConstraints) { }

	[CalledBy(Type = typeof(XSDSchema), Member = "HandleKeyref", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(XmlSchemaKeyref)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(DataRelation), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	public DataRelation(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns) { }

	[CalledBy(Type = typeof(DataSet), Member = "DeserializeRelations", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelation), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Merger), Member = "MergeRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(XSDSchema), Member = "HandleRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(XmlElement), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(Interlocked), Member = "Increment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Int32&)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataRelation), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	public DataRelation(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns, bool createConstraints) { }

	[Browsable(False)]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Interlocked), Member = "Increment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Int32&)}, ReturnType = typeof(int))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 6)]
	public DataRelation(string relationName, string parentTableName, string childTableName, String[] parentColumnNames, String[] childColumnNames, bool nested) { }

	[Browsable(False)]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Interlocked), Member = "Increment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Int32&)}, ReturnType = typeof(int))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 8)]
	public DataRelation(string relationName, string parentTableName, string parentTableNamespace, string childTableName, string childTableNamespace, String[] parentColumnNames, String[] childColumnNames, bool nested) { }

	[CalledBy(Type = typeof(DataRelation), Member = "set_Nested", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelationCollection), Member = "AddCore", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataTable), Member = "get_ParentRelations", ReturnType = typeof(DataRelationCollection))]
	[Calls(Type = typeof(DataTable), Member = "get_Namespace", ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "InValidNestedRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 5)]
	[CallsUnknownMethods(Count = 17)]
	internal void CheckNamespaceValidityForNestedRelations(string ns) { }

	[CalledBy(Type = typeof(DataRelation), Member = "set_Nested", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataSetRelationCollection), Member = "AddCore", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "Contains", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool), typeof(CultureInfo)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "LoopInNestedRelations", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "SelfnestedDatasetConflictingName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 17)]
	[CallsUnknownMethods(Count = 12)]
	internal void CheckNestedRelations() { }

	[CalledBy(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelation), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataSetRelationCollection), Member = "AddCore", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelationCollection), Member = "AddCore", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(DataKey), Member = "CheckState", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataKey), Member = "ColumnsEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataKey)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ColumnsTypeMismatch", ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "KeyColumnsIdentical", ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "RelationDataSetMismatch", ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 8)]
	internal void CheckState() { }

	[CallerCount(Count = 47)]
	[Calls(Type = typeof(DataRelation), Member = "CheckState", ReturnType = typeof(void))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "BadObjectPropertyAccess", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsUnknownMethods(Count = 4)]
	protected void CheckStateForProperty() { }

	[CalledBy(Type = typeof(DataSet), Member = "Clone", ReturnType = typeof(DataSet))]
	[CalledBy(Type = typeof(DataTable), Member = "ReadXmlSchema", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(XmlReader), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0", "T1"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0", "T1"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataTable), Member = "get_Namespace", ReturnType = typeof(string))]
	[Calls(Type = typeof(DataTableCollection), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(DataTable))]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataColumnCollection), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DataColumn))]
	[Calls(Type = typeof(Interlocked), Member = "Increment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Int32&)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataRelation), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(PropertyCollection), Member = ".ctor", ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 12)]
	[CallsUnknownMethods(Count = 23)]
	internal DataRelation Clone(DataSet destination) { }

	[CalledBy(Type = typeof(DataRelation), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn), typeof(DataColumn), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelation), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelation), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet)}, ReturnType = typeof(DataRelation))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(DataCommonEventSource), Member = "EnterScope", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(object), typeof(bool)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(int), typeof(object), typeof(bool)}, ReturnType = typeof(long))]
	[Calls(Type = typeof(DataKey), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRelation), Member = "CheckState", ReturnType = typeof(void))]
	[Calls(Type = typeof(EventSource), Member = "WriteEvent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(long)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ParentOrChildColumnsDoNotHaveDataSet", ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "KeyLengthMismatch", ReturnType = typeof(Exception))]
	[CallsUnknownMethods(Count = 20)]
	private void Create(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns, bool createConstraints) { }

	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	internal bool get_CheckMultipleNested() { }

	[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
	internal String[] get_ChildColumnNames() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
	public override DataColumn[] get_ChildColumns() { }

	[CallerCount(Count = 20)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[DeduplicatedMethod]
	internal DataColumn[] get_ChildColumnsReference() { }

	[CallerCount(Count = 20)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[DeduplicatedMethod]
	internal DataKey get_ChildKey() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	public override ForeignKeyConstraint get_ChildKeyConstraint() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 2)]
	public override DataTable get_ChildTable() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	public override DataSet get_DataSet() { }

	[CalledBy(Type = typeof(Merger), Member = "MergeRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ForeignKeyConstraint), typeof(bool)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(PropertyCollection), Member = ".ctor", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 1)]
	public PropertyCollection get_ExtendedProperties() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	public override bool get_Nested() { }

	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	internal int get_ObjectID() { }

	[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
	internal String[] get_ParentColumnNames() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
	public override DataColumn[] get_ParentColumns() { }

	[CallerCount(Count = 62)]
	[DeduplicatedMethod]
	internal DataColumn[] get_ParentColumnsReference() { }

	[CalledBy(Type = typeof(DataColumn), Member = "set_DataType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataColumn), Member = "IsInRelation", ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(Merger), Member = "MergeRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RelationshipConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation), typeof(XmlDocument)}, ReturnType = typeof(XmlElement))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
	[CallerCount(Count = 21)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	internal DataKey get_ParentKey() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	public override UniqueConstraint get_ParentKeyConstraint() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 2)]
	public override DataTable get_ParentTable() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	public override string get_RelationName() { }

	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "CheckCanRemoveParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRow)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(DataRow), Member = "GetRecordFromVersion", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRowVersion)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataKey), Member = "GetKeyValues", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(Object[]))]
	[Calls(Type = typeof(DataStorage), Member = "IsObjectNull", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataKey), Member = "GetIndexDesc", ReturnType = typeof(IndexField[]))]
	[Calls(Type = typeof(DataTable), Member = "GetIndex", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IndexField[]), typeof(DataViewRowState), typeof(IFilter)}, ReturnType = typeof(Index))]
	[Calls(Type = typeof(Index), Member = "GetRows", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DataRow[]))]
	[Calls(Type = typeof(DataTable), Member = "NewRowArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataRow[]))]
	[CallsUnknownMethods(Count = 2)]
	internal static DataRow[] GetChildRows(DataKey parentKey, DataKey childKey, DataRow parentRow, DataRowVersion version) { }

	[CalledBy(Type = typeof(ForeignKeyConstraint), Member = "CheckConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRow), typeof(DataRowAction)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(DataRow), Member = "HasVersion", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRowVersion)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataRow), Member = "GetRecordFromVersion", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRowVersion)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataKey), Member = "GetKeyValues", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(Object[]))]
	[Calls(Type = typeof(DataRelation), Member = "IsKeyNull", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataKey), Member = "GetSortIndex", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataViewRowState)}, ReturnType = typeof(Index))]
	[Calls(Type = typeof(Index), Member = "FindRecords", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(Range))]
	[Calls(Type = typeof(Range), Member = "get_IsNull", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Range), Member = "get_Count", ReturnType = typeof(int))]
	[Calls(Type = typeof(Range), Member = "get_Min", ReturnType = typeof(int))]
	[Calls(Type = typeof(Index), Member = "GetRecord", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(RecordManager), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataRow))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "MultipleParents", ReturnType = typeof(Exception))]
	[CallsUnknownMethods(Count = 4)]
	internal static DataRow GetParentRow(DataKey parentKey, DataKey childKey, DataRow childRow, DataRowVersion version) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataRow), Member = "GetRecordFromVersion", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRowVersion)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataKey), Member = "GetKeyValues", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(Object[]))]
	[Calls(Type = typeof(DataStorage), Member = "IsObjectNull", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataKey), Member = "GetIndexDesc", ReturnType = typeof(IndexField[]))]
	[Calls(Type = typeof(DataTable), Member = "GetIndex", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IndexField[]), typeof(DataViewRowState), typeof(IFilter)}, ReturnType = typeof(Index))]
	[Calls(Type = typeof(Index), Member = "GetRows", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DataRow[]))]
	[Calls(Type = typeof(DataTable), Member = "NewRowArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataRow[]))]
	[CallsUnknownMethods(Count = 2)]
	internal static DataRow[] GetParentRows(DataKey parentKey, DataKey childKey, DataRow childRow, DataRowVersion version) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[CallsDeduplicatedMethods(Count = 6)]
	[CallsUnknownMethods(Count = 2)]
	private bool IsAutoGenerated(DataColumn col) { }

	[CalledBy(Type = typeof(DataRelation), Member = "GetParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataKey), typeof(DataKey), typeof(DataRow), typeof(DataRowVersion)}, ReturnType = typeof(DataRow))]
	[CalledBy(Type = typeof(DataRow), Member = "GetParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation), typeof(DataRowVersion)}, ReturnType = typeof(DataRow))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataStorage), Member = "IsObjectNull", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[CallsUnknownMethods(Count = 2)]
	private static bool IsKeyNull(Object[] values) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0"}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	protected private void OnPropertyChanging(PropertyChangedEventArgs pcevent) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(PropertyChangedEventArgs), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0"}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	protected private void RaisePropertyChanging(string name) { }

	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	internal void set_CheckMultipleNested(bool value) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataCommonEventSource), Member = "EnterScope", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T1", "T2"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T1", "T2"}, ReturnType = typeof(long))]
	[Calls(Type = typeof(DataTable), Member = "IsNamespaceInherited", ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataTable), Member = "get_Namespace", ReturnType = typeof(string))]
	[Calls(Type = typeof(DataRelation), Member = "CheckNamespaceValidityForNestedRelations", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRelation), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[Calls(Type = typeof(ConstraintCollection), Member = "FindForeignKeyConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(DataColumn[])}, ReturnType = typeof(ForeignKeyConstraint))]
	[Calls(Type = typeof(DataRelation), Member = "ValidateMultipleNestedRelations", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataColumnCollection), Member = "UnregisterName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataColumnCollection), Member = "RegisterColumnName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(PropertyChangedEventArgs), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataCommonEventSource), Member = "Trace", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T0"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "T0"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataTable), Member = "set_ElementColumnCount", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRelation), Member = "CheckNestedRelations", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRow), Member = "GetParentRow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation), typeof(DataRowVersion)}, ReturnType = typeof(DataRow))]
	[Calls(Type = typeof(DataTable), Member = "CacheNestedParent", ReturnType = typeof(void))]
	[Calls(Type = typeof(string), Member = "IsNullOrEmpty", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataTable), Member = "get_NestedParentsCount", ReturnType = typeof(int))]
	[Calls(Type = typeof(DataTable), Member = "get_ParentRelations", ReturnType = typeof(DataRelationCollection))]
	[Calls(Type = typeof(DataRow), Member = "CheckForLoops", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool), typeof(CultureInfo)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(string), Member = "Compare", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(StringComparison)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(EventSource), Member = "WriteEvent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(long)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ConstraintViolation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "RelationNestedReadOnly", ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "DatasetConflictingName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "InvalidParentNamespaceinNestedRelation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "TableCantBeNestedInTwoTables", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 36)]
	[CallsUnknownMethods(Count = 98)]
	public override void set_Nested(bool value) { }

	[CallerCount(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[DeduplicatedMethod]
	internal void SetChildKeyConstraint(ForeignKeyConstraint value) { }

	[CallerCount(Count = 0)]
	[CallsUnknownMethods(Count = 1)]
	[DeduplicatedMethod]
	internal void SetDataSet(DataSet dataSet) { }

	[CallerCount(Count = 3)]
	[CallsUnknownMethods(Count = 1)]
	[DeduplicatedMethod]
	internal void SetParentKeyConstraint(UniqueConstraint value) { }

	[CallerCount(Count = 0)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	public virtual string ToString() { }

	[CalledBy(Type = typeof(DataRelation), Member = "set_Nested", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataRelationCollection), Member = "AddCore", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataRelation)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ForeignKeyConstraint), typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(XmlTreeGen), Member = "AutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "TableCantBeNestedInTwoTables", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 15)]
	[CallsUnknownMethods(Count = 29)]
	internal void ValidateMultipleNestedRelations() { }

}

