namespace System.Data;

[DefaultProperty("ConstraintName")]
public class UniqueConstraint : Constraint
{
	private DataKey _key; //Field offset: 0x38
	private Index _constraintIndex; //Field offset: 0x40
	internal bool _bPrimaryKey; //Field offset: 0x48
	internal string _constraintName; //Field offset: 0x50
	internal String[] _columnNames; //Field offset: 0x58

	internal String[] ColumnNames
	{
		[CalledBy(Type = typeof(ConstraintConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
		[CallerCount(Count = 1)]
		[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
		internal get { } //Length: 11
	}

	[ReadOnly(True)]
	public override DataColumn[] Columns
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
		 get { } //Length: 11
	}

	internal DataColumn[] ColumnsReference
	{
		[CallerCount(Count = 38)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
	}

	internal Index ConstraintIndex
	{
		[CallerCount(Count = 12)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
	}

	internal virtual bool InCollection
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(Constraint), Member = "set_InCollection", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CallsUnknownMethods(Count = 1)]
		internal set { } //Length: 71
	}

	public bool IsPrimaryKey
	{
		[CalledBy(Type = typeof(DataTable), Member = "SerializeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext), typeof(int), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(ConstraintCollection), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(ConstraintConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
		[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
		[CallerCount(Count = 4)]
		[CallsDeduplicatedMethods(Count = 2)]
		[CallsUnknownMethods(Count = 1)]
		[ContainsUnimplementedInstructions]
		 get { } //Length: 81
	}

	internal DataKey Key
	{
		[CallerCount(Count = 38)]
		[DeduplicatedMethod]
		internal get { } //Length: 5
	}

	[ReadOnly(True)]
	public virtual DataTable Table
	{
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(DataKey), Member = "get_Table", ReturnType = typeof(DataTable))]
		[CallsDeduplicatedMethods(Count = 1)]
		 get { } //Length: 48
	}

	[CalledBy(Type = typeof(DataColumn), Member = "SetOrdinalInternal", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DataColumn), Member = "set_Unique", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 6)]
	public UniqueConstraint(DataColumn column) { }

	[CalledBy(Type = typeof(ConstraintCollection), Member = "Add", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(XSDSchema), Member = "HandleConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(XmlSchemaIdentityConstraint)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "SetupAutoGenerated", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	public UniqueConstraint(string name, DataColumn[] columns) { }

	[CalledBy(Type = typeof(DataTable), Member = "set_PrimaryKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintCollection), Member = "Add", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	public UniqueConstraint(DataColumn[] columns) { }

	[Browsable(False)]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 2)]
	public UniqueConstraint(string name, String[] columnNames, bool isPrimaryKey) { }

	[CalledBy(Type = typeof(DataTable), Member = "DeserializeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext), typeof(int), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	public UniqueConstraint(string name, DataColumn[] columns, bool isPrimaryKey) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(ConstraintEnumerator), Member = "GetNext", ReturnType = typeof(bool))]
	[Calls(Type = typeof(ForeignKeyConstraintEnumerator), Member = "GetForeignKeyConstraint", ReturnType = typeof(ForeignKeyConstraint))]
	[Calls(Type = typeof(Constraint), Member = "CheckStateForProperty", ReturnType = typeof(void))]
	[Calls(Type = typeof(DataKey), Member = "ColumnsEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataKey)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "NeededForForeignKeyConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint), typeof(ForeignKeyConstraint)}, ReturnType = typeof(Exception))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "RemovePrimaryKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 5)]
	[CallsUnknownMethods(Count = 6)]
	internal virtual bool CanBeRemovedFromCollection(ConstraintCollection constraints, bool fThrowException) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataTable), Member = "get_EnforceConstraints", ReturnType = typeof(bool))]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 1)]
	internal virtual bool CanEnableConstraint() { }

	[CallerCount(Count = 13327)]
	[DeduplicatedMethod]
	internal virtual void CheckCanAddToCollection(ConstraintCollection constraints) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataTable), Member = "get_EnforceConstraints", ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataRow), Member = "HaveValuesChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[])}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(DataRow), Member = "GetDefaultRecord", ReturnType = typeof(int))]
	[Calls(Type = typeof(RBTree`1), Member = "Key", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = "K")]
	[Calls(Type = typeof(Index), Member = "CompareRecords", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(RBTree`1), Member = "Right", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(RBTree`1), Member = "Left", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataRow), Member = "GetColumnValues", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[])}, ReturnType = typeof(Object[]))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ConstraintViolation", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(Object[])}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 3)]
	[CallsUnknownMethods(Count = 4)]
	internal virtual void CheckConstraint(DataRow row, DataRowAction action) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "CheckState", ReturnType = typeof(void))]
	[DeduplicatedMethod]
	internal virtual void CheckState() { }

	[CallerCount(Count = 0)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	internal virtual Constraint Clone(DataSet destination) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataTable), Member = "get_Namespace", ReturnType = typeof(string))]
	[Calls(Type = typeof(DataTableCollection), Member = "IndexOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(bool)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataTableCollection), Member = "IndexOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataTableCollection), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataTable))]
	[Calls(Type = typeof(DataColumnCollection), Member = "IndexOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataColumnCollection), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataColumn))]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Constraint), Member = "get_ExtendedProperties", ReturnType = typeof(PropertyCollection))]
	[CallsDeduplicatedMethods(Count = 8)]
	[CallsUnknownMethods(Count = 18)]
	internal virtual Constraint Clone(DataSet destination, bool ignorNSforTableLookup) { }

	[CalledBy(Type = typeof(DataTable), Member = "CloneTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(DataSet), typeof(bool)}, ReturnType = typeof(DataTable))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataColumnCollection), Member = "IndexOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(DataColumnCollection), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DataColumn))]
	[Calls(Type = typeof(Constraint), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(UniqueConstraint), Member = "Create", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Constraint), Member = "get_ExtendedProperties", ReturnType = typeof(PropertyCollection))]
	[CallsDeduplicatedMethods(Count = 5)]
	[CallsUnknownMethods(Count = 18)]
	internal UniqueConstraint Clone(DataTable table) { }

	[CalledBy(Type = typeof(ConstraintCollection), Member = "Add", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintCollection), Member = "AddUniqueConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintCollection), Member = "BaseRemove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(Index), Member = "RemoveRef", ReturnType = typeof(int))]
	[CallsUnknownMethods(Count = 1)]
	internal void ConstraintIndexClear() { }

	[CalledBy(Type = typeof(ConstraintCollection), Member = "Add", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintCollection), Member = "AddUniqueConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(UniqueConstraint)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DataKey), Member = "GetSortIndex", ReturnType = typeof(Index))]
	[Calls(Type = typeof(Index), Member = "AddRef", ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 2)]
	internal void ConstraintIndexInitialize() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "ContainsColumn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn)}, ReturnType = typeof(bool))]
	internal virtual bool ContainsColumn(DataColumn column) { }

	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataSet), typeof(bool)}, ReturnType = typeof(Constraint))]
	[CalledBy(Type = typeof(UniqueConstraint), Member = "Clone", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable)}, ReturnType = typeof(UniqueConstraint))]
	[CallerCount(Count = 6)]
	[Calls(Type = typeof(DataKey), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataKey), Member = "CheckState", ReturnType = typeof(void))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "ExpressionInConstraint", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn)}, ReturnType = typeof(Exception))]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 7)]
	private void Create(string constraintName, DataColumn[] columns) { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "ColumnsEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataKey)}, ReturnType = typeof(bool))]
	[CallsUnknownMethods(Count = 1)]
	public virtual bool Equals(object key2) { }

	[CalledBy(Type = typeof(ConstraintConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(DataKey), Member = "GetColumnNames", ReturnType = typeof(String[]))]
	internal String[] get_ColumnNames() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "ToArray", ReturnType = typeof(DataColumn[]))]
	public override DataColumn[] get_Columns() { }

	[CallerCount(Count = 38)]
	[DeduplicatedMethod]
	internal DataColumn[] get_ColumnsReference() { }

	[CallerCount(Count = 12)]
	[DeduplicatedMethod]
	internal Index get_ConstraintIndex() { }

	[CalledBy(Type = typeof(DataTable), Member = "SerializeConstraints", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext), typeof(int), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintCollection), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Constraint)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstraintConverter), Member = "ConvertTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(object), typeof(Type)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(XmlTreeGen), Member = "HandleTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataTable), typeof(XmlDocument), typeof(XmlElement), typeof(bool)}, ReturnType = typeof(XmlElement))]
	[CallerCount(Count = 4)]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	public bool get_IsPrimaryKey() { }

	[CallerCount(Count = 38)]
	[DeduplicatedMethod]
	internal DataKey get_Key() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "get_Table", ReturnType = typeof(DataTable))]
	[CallsDeduplicatedMethods(Count = 1)]
	public virtual DataTable get_Table() { }

	[CallerCount(Count = 19)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	public virtual int GetHashCode() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Index), Member = "GetUniqueKeyValues", ReturnType = typeof(Object[]))]
	[Calls(Type = typeof(Index), Member = "FindNodeByKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(Index), Member = "GetRangeFromNode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(Range))]
	[Calls(Type = typeof(Index), Member = "GetRows", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Range)}, ReturnType = typeof(DataRow[]))]
	[Calls(Type = typeof(ExceptionBuilder), Member = "UniqueConstraintViolationText", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn[]), typeof(Object[])}, ReturnType = typeof(string))]
	[Calls(Type = typeof(DataRow), Member = "set_RowError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DataRow), Member = "SetColumnError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DataColumn), typeof(string)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 6)]
	internal virtual bool IsConstraintViolated() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(DataKey), Member = "CheckState", ReturnType = typeof(void))]
	[DeduplicatedMethod]
	private void NonVirtualCheckState() { }

	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Constraint), Member = "set_InCollection", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 1)]
	internal virtual void set_InCollection(bool value) { }

}

