'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210628767,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--no-reset')?'no-reset':process.argv.includes('--no-target-gate')?'no-target-gate':process.argv.includes('--faceup-only')?'faceup-only':process.argv.includes('--no-normal-trigger')?'no-normal-trigger':process.argv.includes('--wrong-owner')?'wrong-owner':process.argv.includes('--no-type')?'no-type':process.argv.includes('--no-column')?'no-column':null;
 for(const test of [{},{occupied:true},{stolen:true},{normal:true},{facedownTarget:true},{noTarget:true},{reset:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:33}],[filler,{...base,code:filler}],[spellCost,{...base,code:spellCost,type:0x20004}],[recipient,{...base,code:recipient,type:2}]]);
  const reader=name=>{
   if(name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function(e,tp) '+(test.stolen?'local t=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_MZONE,0,nil,'+lab+'):GetFirst() Duel.GetControl(t,1-tp) ':'')+'local c=Duel.GetMatchingGroup(Card.IsCode,tp,'+(test.normal?'LOCATION_HAND':'LOCATION_GRAVE')+',0,nil,'+boss+'):GetFirst() '+(test.normal?'Duel.Summon(tp,c,true,nil)':'Duel.SpecialSummon(c,0,tp,tp,false,false,POS_FACEUP)')+' end) c:RegisterEffect(e) local p=Effect.CreateEffect(c) p:SetType(EFFECT_TYPE_IGNITION) p:SetRange(LOCATION_GRAVE) p:SetOperation(function(e,tp) local a=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_SZONE,0,nil,'+boss+'):GetFirst() local b=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_SZONE,LOCATION_SZONE,nil,'+lab+'):GetFirst() if a and b and a:IsFaceup() and b:IsFaceup() and a:IsType(TYPE_TRAP) and a:IsType(TYPE_CONTINUOUS) and not a:IsType(TYPE_MONSTER) and b:IsType(TYPE_TRAP) and b:IsType(TYPE_CONTINUOUS) and not b:IsType(TYPE_MONSTER) then Duel.Hint(HINT_NUMBER,tp,703) end '+(test.reset?'Duel.Destroy(Group.FromCards(a,b),REASON_EFFECT) if a:IsLocation(LOCATION_GRAVE) and b:IsLocation(LOCATION_GRAVE) and a:IsType(TYPE_MONSTER) and b:IsType(TYPE_MONSTER) and not a:IsType(TYPE_TRAP) and not b:IsType(TYPE_TRAP) then Duel.Hint(HINT_NUMBER,tp,704) end ':'')+'end) c:RegisterEffect(p) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='no-reset')lua=lua.replace('e1:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET)','do end');if(control==='no-target-gate')lua=lua.replace('Duel.IsExistingTarget(s.tgfilter,tp,0,LOCATION_MZONE,1,nil)','true');if(control==='faceup-only')lua=lua.replace('return (c:GetOriginalType()&TYPE_MONSTER)~=0 and not c:IsForbidden()','return c:IsFaceup() and (c:GetOriginalType()&TYPE_MONSTER)~=0 and not c:IsForbidden()');if(control==='no-normal-trigger')lua=lua.replace('c:RegisterEffect(e1)','do end');if(control==='wrong-owner')lua=lua.replace('local p=c:GetOwner()','local p=c:GetControler()');if(control==='no-type')lua=lua.replace(/e1:SetValue\(TYPE_TRAP\+TYPE_CONTINUOUS\)\s+c:RegisterEffect\(e1\)/,'e1:SetValue(TYPE_TRAP+TYPE_CONTINUOUS)');if(control==='no-column')lua=lua.replace('Duel.MoveSequence(c,sq)','do end');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,placementStarted=false,placementFinished=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   add(boss,test.normal?L.HAND:L.GRAVE,0,P.FACEUP_ATTACK);if(test.normal){add(filler,L.MZONE,0,P.FACEUP_ATTACK,0);add(filler,L.MZONE,0,P.FACEUP_ATTACK,1);}add(recipient,L.HAND);if(!test.noTarget)add(lab,L.MZONE,test.stolen?0:1,test.facedownTarget?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK,3);if(test.occupied){add(spellCost,L.SZONE,0,P.FACEUP_ATTACK,2);add(spellCost,L.SZONE,1,P.FACEUP_ATTACK,3);}for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=(location,controller=0)=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON|Q.POSITION,controller,location}).map((c,sequence)=>c?{...c,sequence}:null).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(test.reset&&secondary){assert(trace.some(m=>m.type===M.HINT&&String(m.hint)==='703'),'Prior native Trap conversion');assert(trace.some(m=>m.type===M.HINT&&String(m.hint)==='704'),'Both cards restore native Monster type in GY');for(const [code,player] of [[boss,0],[lab,1]]){const card=query(L.GRAVE,player).find(c=>c.code===code);assert(card&&(card.reason&1)&&(card.reason&0x40),'Actual effect destruction to GY');}done=true;continue;}if(!activated){const index=p.activates.findIndex(c=>c.code===recipient);assert(index>=0,'Neutral real summon available');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(test.noTarget){assert(query(L.MZONE).some(c=>c.code===boss),'Whale summon succeeds without opponent target');assert(!query(L.SZONE).some(c=>c.code===boss),'No targetless source placement');assert(!trace.some(m=>m.type===M.CHAINING&&m.code===boss),'No targetless summon trigger activation');done=true;continue;}if(test.normal){assert.equal(query(L.GRAVE).filter(c=>c.code===filler).length,2,'Both real Tributes sent to GY');assert(query(L.GRAVE).filter(c=>c.code===filler).every(c=>(c.reason&2)&&(c.reason&0x10)),'Native release and summon reasons');assert(trace.some(m=>m.type===M.SUMMONED),'Native Normal Summon completed');}assert(query(L.SZONE).some(c=>c.code===boss),'Whale actual SZONE placement');assert(query(L.SZONE,test.stolen?0:1).some(c=>c.code===lab),'Target actual owner SZONE placement');assert.equal(query(L.SZONE).find(c=>c.code===boss).sequence,2,'Whale remains in column2');assert.equal(query(L.SZONE,test.stolen?0:1).find(c=>c.code===lab).sequence,test.stolen?1:3,'Target returns to owner in matching column');assert(!query(L.MZONE).some(c=>c.code===boss),'Whale left MZONE');assert(!query(L.MZONE,1).some(c=>c.code===lab),'Target left MZONE');if(test.occupied)for(const player of [0,1]){const cost=query(L.GRAVE,player).find(c=>c.code===spellCost);assert(cost&&(cost.reason&1)&&(cost.reason&0x40),'Occupied card actually destroyed');}if(!secondary){const index=p.activates.findIndex(c=>c.code===recipient&&c.location===L.GRAVE);assert(index>=0,'Native type probe available');secondary=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(trace.some(m=>m.type===M.HINT&&String(m.hint)==='703'),'Both cards are native Continuous Traps and not current Monsters');done=true;}
    else if(p.type===M.SELECT_TRIBUTE){assert(test.normal,'Real Tribute summon');assert.equal(p.min,2,'Level8 requires two Tributes');core.duelSetResponse(duel,{type:R.SELECT_TRIBUTE,indicies:[0,1]});}
    else if(p.type===M.SELECT_CARD){if(test.stolen){assert(query(L.MZONE,1).some(c=>c.code===lab&&c.sequence===3),'Actual opponent control at column3');assert(!query(L.MZONE).some(c=>c.code===lab),'Target no longer controlled by owner');}const index=p.selects.findIndex(c=>c.code===lab);assert(index>=0,'Actual opponent target');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_EFFECTYN)core.duelSetResponse(duel,{type:R.SELECT_EFFECTYN,yes:true});
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const places=[];for(const player of [0,1])for(const location of [L.MZONE,L.SZONE])for(const sequence of (test.stolen&&player===1?[3,2,0,1,4]:[2,0,1,3,4])){const bit=(player===p.player?0:16)+(location===L.SZONE?8:0)+sequence;if((p.field_mask&(1<<bit))===0)places.push({player,location,sequence});}assert(places.length,'Legal placement');core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[places[0]]});}
    else if(p.type===M.SELECT_CHAIN){const index=p.selects.findIndex(c=>c.code===boss);core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/crewal-whale-placement'+(control?'-'+control:'')+'.json'),JSON.stringify({engine:'Public OCGCore, full production Battle Preparation/candidate metadata; neutral cost and Deck targets. Actual Whale summon-trigger placement; neutral summon/target/occupied cards; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
