'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/fresh-ccg-september'),source=path.join(root,'public/CCG Downloads/CCG_Scripts/c215068354.lua');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const plans=[{control:null,failed:[]},{control:'no-summon',failed:[{cards:1},{cards:2}]},{control:'no-shuffle',failed:[{cards:1},{cards:2}]}].map(p=>({...p,h:'hand',artifact:'hand',cases:4}));
plans.push(...[{control:null,failed:[]},{control:'no-search',failed:[{cards:1},{cards:2},{cards:2,shortage:true}]},{control:'flat-count',failed:[{cards:2}]}].map(p=>({...p,h:'standby',artifact:'standby',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'no-set',failed:[{cards:1},{cards:2}]},{control:'no-same-turn',failed:[{cards:1},{cards:2}]}].map(p=>({...p,h:'reveal',artifact:'reveal-set-message-adapter-public-qp-adapter',cases:2,args:['--public-qp-adapter','--public-set-message-adapter']})));
plans.push(...[{control:null,failed:[]},{control:'no-send',failed:[{cards:1}]},{control:'any-set',failed:[{cards:1,wrongSet:true},{cards:1,absent:true}]}].map(p=>({...p,h:'summon_send',artifact:'summon-send',cases:4})));
plans.push(...[{control:null,failed:[]},{control:'no-recovery',failed:[{cards:1},{cards:1,spell:true,set:true},{cards:1,spell:true}]},{control:'any-name',failed:[{cards:1,wrongSet:true},{cards:1,sameName:true}]},{control:'any-set',failed:[{cards:1,wrongSet:true}]}].map(p=>({...p,h:'recovery',artifact:'recovery',cases:6})));
plans.push(...[{control:null,failed:[]},{control:'no-send',failed:[{cards:1}]},{control:'no-normal-trigger',failed:[{cards:1}]}].map(p=>({...p,h:'normal_summon',artifact:'normal-summon',cases:4})));
plans.push(...[{control:null,failed:[]},{control:'no-hand-limit',failed:[{cards:1},{cards:1,decline:true}]},{control:'per-copy-limit',failed:[{cards:1},{cards:1,decline:true}]}].map(p=>({...p,h:'count',artifact:'count',cases:2})));
plans.push(...[{control:null,failed:[]},{control:'no-renewal',failed:[{cards:1,decline:true}]}].map(p=>({...p,h:'renewal',artifact:'renewal',cases:1})));
plans.push(...[{control:null,failed:[]},{control:'no-relation',failed:[{mode:'leave'},{mode:'return'}]},{control:'no-interruption',failed:[{mode:'leave'},{mode:'return'},{mode:'negate'}]}].map(p=>({...p,h:'interrupt',artifact:'interrupt',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'no-recovery',failed:[{cards:1,spell:true,set:true},{cards:1,spell:true}]}].map(p=>({...p,h:'canonical_recovery',artifact:'canonical-recovery',cases:2})));
// Regenerate the isolated decoder from the current wrapper before recording evidence.
const adapterGeneration=JSON.parse(execFileSync('python',[path.join(__dirname,'fresh_public_set_message_adapter.py')],{cwd:root,encoding:'utf8',timeout:10000}));
const runtimeDir=path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist');
const dependencyFiles=[...['constant.lua','utility.lua','procedure.lua'].map(n=>path.join(root,'tmp/omega_scripts',n)),...fs.readdirSync(runtimeDir).filter(n=>/\.(js|wasm)$/.test(n)).map(n=>path.join(runtimeDir,n)),path.join(out,'public-core-set-message-adapter.mjs'),path.join(__dirname,'fresh_public_set_message_adapter.py')];
dependencyFiles.push(...[217029078,233212369].map(code=>path.join(root,'public/CCG Downloads/CCG_Scripts/c'+code+'.lua')));
const dependencies=Object.fromEntries(dependencyFiles.map(f=>[path.relative(root,f).replaceAll('\\','/'),hash(f)]));
const verifyDependencies=()=>{for(const [relative,sha] of Object.entries(dependencies))assert.equal(hash(path.join(root,relative)),sha,'Runtime dependency changed during batch: '+relative);};
assert.equal(adapterGeneration.source_sha256,hash(path.join(runtimeDir,'index.js')));
assert.equal(adapterGeneration.adapter_sha256,hash(path.join(out,'public-core-set-message-adapter.mjs')));
plans.push(...[{control:null,failed:[]},{control:'no-trigger-limit',failed:[{cards:1},{cards:1,normal:true}]},{control:'per-copy-limit',failed:[{cards:1},{cards:1,normal:true}]}].map(p=>({...p,h:'trigger_count',artifact:'trigger-count',cases:2})));
const database=path.join(out,'candidate-CCG_v1.db'),databaseHash=hash(database);
const sourceHash=hash(source),runs=[];
for(const plan of plans){
 verifyDependencies();
 const harness=path.join(__dirname,'fresh_janna_'+plan.h+'.cjs'),harnessHash=hash(harness);
 const started=Date.now(),args=['--no-warnings',harness,...(plan.args||[]),...(plan.control?['--'+plan.control]:[])];let status=0;
 try{execFileSync(process.execPath,args,{cwd:root,timeout:30000,stdio:'pipe'});}catch(e){assert.equal(e.signal,null,'Timed out/terminated child');status=e.status;}
 const file=path.join(out,'janna-'+(plan.artifact||plan.h)+(plan.control?'-'+plan.control:'')+'.json');assert(fs.statSync(file).mtimeMs>=started-2000,'Stale result');const result=JSON.parse(fs.readFileSync(file,'utf8'));
 assert.equal(result.script_sha256,sourceHash);if(plan.support)assert.equal(result.supporting_script_sha256,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c'+plan.support+'.lua')));if(plan.args&&plan.args.includes('--official'))assert.equal(result.supporting_script_sha256,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c246380598.lua')));if(plan.args?.includes('--canonical-arms')){assert.equal(result.canonical_arms,true);assert.deepEqual(Object.keys(result.supporting_scripts_sha256).sort(),[...new Set(result.results.map(r=>String(r.test.arm)))].sort());for(const [code,sha] of Object.entries(result.supporting_scripts_sha256))assert.equal(sha,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c'+code+'.lua')));}if(plan.h==='reveal'){assert.equal(result.public_qp_adapter,true);assert.equal(result.public_set_message_adapter,true);assert.equal(result.set_message_adapter_sha256,hash(path.join(out,'public-core-set-message-adapter.mjs')));}if(plan.h==='canonical_recovery'){assert.deepEqual(Object.keys(result.supporting_scripts_sha256).sort(),['217029078','233212369']);for(const [code,sha] of Object.entries(result.supporting_scripts_sha256))assert.equal(sha,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c'+code+'.lua')));}assert.equal(result.results.length,plan.cases);assert.deepEqual(result.results.filter(r=>r.failure).map(r=>r.test),plan.failed);assert.equal(status,plan.failed.length?1:0);assert.equal(hash(source),sourceHash);assert.equal(hash(harness),harnessHash);
 verifyDependencies();assert.equal(hash(database),databaseHash);runs.push({harness:plan.h,harness_sha256:harnessHash,control:plan.control,status,expected_failures:plan.failed,artifact_sha256:hash(file)});
}
fs.writeFileSync(path.join(out,'janna-batch.json'),JSON.stringify({scope:'Janna fullsource hand shuffle/SpecialSummon4cases plus next Standby search2cases and revealed Spell/QuickPlaySet/same-turnactivation2cases with explicit test-only public constant/message adapters; actual SpecialSummon Decksend trigger4cases; optional GYrecovery6cases; legal Level6 NormalSummon trigger4cases; sharedhandHOPT/separateSummontrigger2cases; actual ownturn3HandSSrenewal1case; actual CL1hand/CL2Trap interruptions3cases; NormalSpecial cross-copy summontriggerHOPT2cases; fullcanonical Cloudwing/DivineWhirlwind recovery2cases with exact control failures; reveal/deferred effects/native Omega remain open',script_sha256:sourceHash,candidate_database_sha256:databaseHash,runtime_dependencies_sha256:dependencies,adapter_generation:adapterGeneration,runs},null,2)+'\n');console.log(JSON.stringify({runs:runs.length,baseline_cases:33,status:'PASS'}));
