'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210506870,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--no-material-send')?'no-material-send':process.argv.includes('--no-count')?'no-count':null;
 for(const test of [{},{field:true},{wrongRace:true},{wrongAttribute:true},{absent:true},{opponent:true},{grave:true},{field:true,facedown:true},{count:true},{materialLost:true},{sourceLost:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:33}],[filler,{...base,code:filler}],[recipient,{...base,code:recipient,type:65,race:test.wrongRace?1n:128n,attribute:test.wrongAttribute?1:32}]]);
  cards.set(spellCost,{...base,code:spellCost,type:33});
  const reader=name=>{
   if((test.materialLost||test.sourceLost)&&name==='c'+spellCost+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_CHAINING) e:SetCountLimit(1) e:SetCondition(function(e,tp,eg,ep,ev,re) return re:GetHandler():IsCode('+boss+') end) e:SetOperation(function(e,tp) local c=Duel.GetMatchingGroup(Card.IsCode,tp,0,'+(test.sourceLost?'LOCATION_MZONE':'LOCATION_HAND')+',nil,'+(test.sourceLost?boss:lab)+'):GetFirst() Duel.Remove(c,POS_FACEUP,REASON_EFFECT) end) c:RegisterEffect(e) end';
   if(name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) c:EnableReviveLimit() local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_SINGLE) e:SetCode(EFFECT_FUSION_MATERIAL) e:SetCondition(function(e,g,gc,chkfnf) if not g then return false end return g:IsExists(Card.IsCode,1,nil,'+lab+') and g:IsExists(Card.IsCode,1,nil,'+filler+') end) e:SetOperation(function(e,tp,eg) local g=Group.FromCards(eg:Filter(Card.IsCode,nil,'+lab+'):GetFirst(),eg:Filter(Card.IsCode,nil,'+filler+'):GetFirst()) Duel.SetFusionMaterial(g) end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='no-count')lua=lua.replace('e5:SetCountLimit(1,id+200)','do end');
    if(control==='no-material-send')lua=lua.replace('Duel.SendtoGrave(mat,REASON_EFFECT+REASON_MATERIAL+REASON_FUSION)','do end');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,placementStarted=false,placementFinished=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   if(test.materialLost||test.sourceLost)add(spellCost,L.MZONE,1,P.FACEUP_ATTACK);if(test.count){add(boss,L.MZONE,0,P.FACEUP_ATTACK,2);add(recipient,L.EXTRA);add(lab,L.HAND);add(filler,L.HAND);}
   add(boss,L.MZONE,0,P.FACEUP_ATTACK,0);add(recipient,L.EXTRA,0,P.FACEDOWN_DEFENSE);if(!test.absent)add(lab,test.grave?L.GRAVE:test.field?L.MZONE:L.HAND,test.opponent?1:0,test.facedown?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK,1);add(filler,L.HAND);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){const index=p.activates.findIndex(c=>c.code===boss&&c.location===L.MZONE&&String(c.description)===String(132506870n*16n+2n));if(!activated){assert.equal(index>=0,!test.wrongRace&&!test.wrongAttribute&&!test.absent&&!test.opponent&&!test.grave,'Printed Fusion activation availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(test.materialLost||test.sourceLost)assert(trace.some(m=>m.type===M.CHAINING&&m.code===spellCost&&m.chain_size===2),'Actual opponent interruption CL2');if(test.materialLost){assert(query(L.REMOVED).some(c=>c.code===lab),'Required material actually banished');assert(query(L.HAND).some(c=>c.code===filler),'Other material retained Hand');assert(query(L.EXTRA).some(c=>c.code===recipient),'Fusion remains Extra');assert(!query(L.MZONE).some(c=>c.code===recipient),'No Fusion after required material loss');done=true;continue;}assert(query(L.MZONE).some(c=>c.code===recipient),'Actual Fusion target summoned');for(const code of [lab,filler]){const mat=query(L.GRAVE).find(c=>c.code===code);assert(mat,'Actual Fusion material in GY');assert(mat.reason&0x40,'Material sent as effect');assert(mat.reason&8,'Native material reason');assert(mat.reason&0x40000,'Native Fusion reason');}assert(trace.some(m=>m.type===M.SPSUMMONED),'Native summon complete');if(test.sourceLost)assert(query(L.REMOVED).some(c=>c.code===boss),'Monster source actually banished while Fusion resolves');else assert(query(L.MZONE).some(c=>c.code===boss),'Heat retained on field');if(test.count){assert.equal(query(L.MZONE).filter(c=>c.code===boss).length,2,'Two full production sources retained');assert(query(L.EXTRA).some(c=>c.code===recipient),'Second legal Fusion target retained');for(const code of [lab,filler])assert(query(L.HAND).some(c=>c.code===code),'Second legal material set retained');if(turn===1)assert(index<0,'Shared Fusion HOPT blocks both copies');if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}assert(index>=0,'Fusion activation renews next own turn');}done=true;}
    else if(p.type===M.SELECT_CARD){core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:p.selects.map((_,i)=>i).slice(0,p.min)});}
    else if(p.type===M.SELECT_UNSELECT_CARD)core.duelSetResponse(duel,{type:R.SELECT_UNSELECT_CARD,index:p.selectable.length?0:null});
    else if(p.type===M.SELECT_YESNO)core.duelSetResponse(duel,{type:R.SELECT_YESNO,yes:false});
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.MZONE,sequence}]});}
    else if(p.type===M.SELECT_CHAIN){const index=p.player===1&&(test.materialLost||test.sourceLost)?p.selects.findIndex(c=>c.code===spellCost):-1;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/talismandrake-heat-fusion'+(control?'-'+control:'')+'.json'),JSON.stringify({adapter:null,engine:'Public OCGCore, full production Talismandrake Heat/candidate metadata; neutral supporting cards. Actual production Fusion ignition with neutral direct EFFECT_FUSION_MATERIAL two-code recipe; pinned helper compatibility not covered; source seeded MZONE, native Omega unverified; native Omega unverified; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
