'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210175845,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--no-count')?'no-count':process.argv.includes('--short-targets')?'short-targets':process.argv.includes('--fixed-one')?'fixed-one':process.argv.includes('--wrong-count')?'wrong-count':process.argv.includes('--no-cost')?'no-cost':process.argv.includes('--no-partner')?'no-partner':null;
 for(const test of [{},{absentPartner:true},{wrongPartner:true},{facedownPartner:true},{noOpponent:true},{chain:2},{chain:3},{chain:3,scarce:true},{count:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:33,setcodes:test.wrongPartner?[]:[0x52f8]}],[filler,{...base,code:filler}],[spellCost,{...base,code:spellCost,type:0x20002}],[recipient,{...base,code:recipient,type:2}]]);
  const reader=name=>{
   if(test.chain&&name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function() end) c:RegisterEffect(e) end';
   if(test.chain===3&&name==='c'+lab+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_FREE_CHAIN) e:SetCountLimit(1) e:SetOperation(function() end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='no-count')lua=lua.replace('e1:SetCountLimit(1,id)','do end');if(control==='short-targets')lua=lua.replace('ct=ct+1','ct=ct');if(control==='fixed-one')lua=lua.replace('e:SetLabel(ct)','e:SetLabel(1)');if(control==='wrong-count')lua=lua.replace('e:SetLabel(ct)','e:SetLabel(ct+1)');if(control==='no-cost')lua=lua.replace('Duel.SendtoGrave(c,REASON_COST)','do end');if(control==='no-partner')lua=lua.replace('Duel.IsExistingMatchingCard(s.otherfilter,tp,LOCATION_MZONE,0,1,nil,e:GetHandler())','true');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,chainStarted=false,rejected=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   if(test.chain)add(recipient,L.HAND);add(boss,L.MZONE,0,P.FACEUP_ATTACK);if(test.count)add(boss,L.MZONE,0,P.FACEUP_ATTACK,2);if(!test.absentPartner)add(lab,L.MZONE,0,test.facedownPartner?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK,1);if(!test.noOpponent){add(filler,L.MZONE,1,P.FACEUP_ATTACK);add(spellCost,L.SZONE,1,P.FACEUP_ATTACK);if(test.chain===3&&!test.scarce)add(filler,L.MZONE,1,P.FACEUP_ATTACK,1);}for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=(location,controller=0)=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(test.scarce&&chainStarted){assert(rejected,'Native CL3 rejection observed');assert(!activated,'Source did not activate');assert(query(L.MZONE).some(c=>c.code===boss),'Rejected source stays MZONE');assert(!query(L.GRAVE).some(c=>c.code===boss),'No GY cost paid');assert.equal(query(L.GRAVE,1).length,0,'Opponent cards retained');done=true;continue;}if(test.chain&&!chainStarted){const index=p.activates.findIndex(c=>c.code===recipient);assert(index>=0,'Neutral chain starter available');chainStarted=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(!activated){const index=p.activates.findIndex(c=>c.code===boss);assert.equal(index>=0,!test.absentPartner&&!test.wrongPartner&&!test.facedownPartner&&!test.noOpponent,'Quick destruction availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(trace.some(m=>m.type===M.CHAINING&&m.code===boss&&m.chain_size===(test.chain||1)),'Native Principality chain position');const source=query(L.GRAVE).find(c=>c.code===boss);assert(source,'Principality actually sent to GY');assert(source.reason&0x80,'Actual source COST');const destroyed=query(L.GRAVE,1).filter(c=>c.code===filler||c.code===spellCost);assert.equal(destroyed.length,test.chain||1,'Exact opponent destruction count');assert(destroyed[0].reason&0x40,'Actual effect reason');assert(destroyed[0].reason&1,'Actual destruction reason');assert(query(L.MZONE).some(c=>c.code===lab),'Other Scarstech retained');if(test.count){assert.equal(query(L.MZONE).filter(c=>c.code===boss).length,1,'Second production copy retained');assert.equal(query(L.MZONE,1).length+query(L.SZONE,1).length,1,'Legal opponent card retained');if(turn===1)assert(!p.activates.some(c=>c.code===boss&&c.location===L.MZONE),'Shared destruction limit blocks second copy');if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}assert(p.activates.some(c=>c.code===boss&&c.location===L.MZONE),'Destruction available next own turn');}done=true;}
    else if(p.type===M.SELECT_CARD){assert.equal(p.min,test.chain||1,'Exact chain selection minimum');assert.equal(p.max,test.chain||1,'Exact chain selection maximum');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:Array.from({length:test.chain||1},(_,i)=>i)});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.SZONE,sequence}]});}
    else if(p.type===M.SELECT_CHAIN){let index=-1;if(test.chain&&chainStarted&&!activated&&!rejected&&p.player===0){const current=trace.filter(m=>m.type===M.CHAINING).length;const wanted=test.chain===3&&current===1?lab:boss;index=p.selects.findIndex(c=>c.code===wanted&&c.location===L.MZONE);if(test.scarce&&wanted===boss){assert.equal(index,-1,'CL3 rejects only two opponent targets');rejected=true;}if(index>=0&&wanted===boss)activated=true;}core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/scarstech-principality-destruction'+(control?'-'+control:'')+'.json'),JSON.stringify({engine:'Public OCGCore; full production Principality/candidate metadata, neutral partner/opponent cards. Actual Chain Link1 destruction and cost; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
