'use strict';
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{DatabaseSync}=require('node:sqlite');
const ROOT=path.resolve(__dirname,'..'),CUSTOM=path.join(ROOT,'public/CCG Downloads/CCG_Scripts'),OMEGA=path.join(ROOT,'tmp/omega_scripts');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=216532402,ritual=900000901,material=900000902,filler=900000903,macro=30241314;
 const db=new DatabaseSync(path.join(ROOT,'output/fresh-ccg-september/candidate-CCG_v1.db'),{readOnly:true}),row=db.prepare('select * from datas where id=?').get(boss);db.close();
 const base={alias:0,setcodes:[],type:33,level:2,attribute:8,race:2n,attack:300,defense:200,lscale:0,rscale:0,link_marker:0},results=[];
 for(const test of [{},{deck:true},{unrelated:true},{wrongSum:true},{deck:true,largeRitual:true},{deck:true,occupied:true},{deck:true,macro:true},{two:true}]){
  const legal=!test.unrelated&&!test.wrongSum&&!test.occupied,logs=[],trace=[],cards=new Map([[boss,{...base,code:boss,setcodes:[0x11f],type:Number(row.type),level:0}],[ritual,{...base,code:ritual,setcodes:[0x11f],type:0xa1,level:test.largeRitual?8:test.two?4:2}],[material,{...base,code:material,setcodes:test.unrelated?[]:[0x11f],level:test.wrongSum?1:2}],[filler,{...base,code:filler}],[macro,{...base,code:macro,type:0x20004,level:0}]]);
  const reader=name=>{if(name===`c${ritual}.lua`)return `local s,id=GetID() function s.initial_effect(c) c:EnableReviveLimit() local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F) e:SetCode(EVENT_SPSUMMON_SUCCESS) e:SetOperation(function(e,tp) local c=e:GetHandler() assert(c:IsSummonType(SUMMON_TYPE_RITUAL),'Not an actual Ritual Summon') local mat=c:GetMaterial() assert(#mat==${test.two?2:1},'Recorded material count mismatch') assert(mat:FilterCount(Card.IsReason,nil,REASON_RELEASE)==${test.two?2:1},'Recorded material is not Tributed') Duel.Damage(tp,377,REASON_EFFECT) end) c:RegisterEffect(e) end`;if(name===`c${material}.lua`)return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F) e:SetCode(EVENT_RELEASE) e:SetProperty(EFFECT_FLAG_DELAY) e:SetOperation(function(e,tp) Duel.Damage(tp,177,REASON_EFFECT) end) c:RegisterEffect(e) end';if([filler].some(c=>name===`c${c}.lua`))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';const file=[path.join(CUSTOM,name),path.join(OMEGA,name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let source=fs.readFileSync(file,'utf8');if(name===`c${boss}.lua`&&process.argv.includes('--old-relation'))source=source.replace('rc:IsLocation(LOCATION_HAND) and Duel.SpecialSummon','rc:IsRelateToEffect(e) and Duel.SpecialSummon');if(name===`c${boss}.lua`&&process.argv.includes('--deck-api'))source=source.replace('if Duel.SendtoGrave(mat,REASON_EFFECT+REASON_RELEASE+REASON_MATERIAL+REASON_RITUAL)==0 then return end','Duel.ReleaseRitualMaterial(mat,true)');if(name===`c${boss}.lua`&&process.argv.includes('--old-deck-release'))source=source.replace('Duel.SendtoGrave(mat,REASON_EFFECT+REASON_RELEASE+REASON_MATERIAL+REASON_RITUAL)','Duel.Release(mat,REASON_EFFECT+REASON_MATERIAL+REASON_RITUAL)');if(name===`c${boss}.lua`&&process.argv.includes('--ordinary-send'))source=source.replace('REASON_EFFECT+REASON_RELEASE+REASON_MATERIAL+REASON_RITUAL','REASON_EFFECT+REASON_MATERIAL+REASON_RITUAL');return source};
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position:P.FACEUP_ATTACK});add(boss,L.HAND);add(ritual,L.HAND);add(material,test.deck?L.DECK:L.MZONE);if(test.two)add(material,L.MZONE,0,1);if(test.occupied)add(filler,L.MZONE);if(test.macro)add(macro,L.SZONE,1,2);for(const player of [0,1])for(let i=0;i<5;i++)add(filler,L.DECK,player);
   core.startDuel(duel);
   for(let step=0;step<120&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));if(state===S.END)throw Error('Duel ended');if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){const index=p.activates.findIndex(c=>c.code===boss&&c.location===L.HAND);if(legal&&!activated){if(index<0)throw Error('Ritual activation unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(!legal&&index>=0)throw Error('Illegal Ritual activation offered');if(legal){const field=core.duelQueryLocation(duel,{flags:Q.CODE|Q.STATUS,controller:0,location:L.MZONE}),gy=core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location:test.macro?L.REMOVED:L.GRAVE});if(!field.some(c=>c?.code===ritual))throw Error('Actual Ritual Summon failed');const summoned=field.find(c=>c?.code===ritual);if((summoned.status&8)===0)throw Error('Proper Ritual Summon flag missing');const mat=gy.find(c=>c?.code===material);if(!mat||(mat.reason&0x2)===0||(mat.reason&0x100000)===0)throw Error('Material not Tributed');if(trace.filter(t=>t.type===M.DAMAGE&&t.amount===177).length!==(test.two?2:1))throw Error('Actual EVENT_RELEASE trigger did not resolve once');if(trace.filter(t=>t.type===M.DAMAGE&&t.amount===377).length!==1)throw Error('Ritual material-count probe did not resolve');if(!trace.some(t=>t.type===M.SPSUMMONING&&t.code===ritual))throw Error('No Summon message');}done=true;}
    else if(p.type===M.SELECT_CARD){const wanted=p.selects.some(c=>c.code===ritual)?ritual:material,index=p.selects.findIndex(c=>c.code===wanted);if(index<0)throw Error('Candidate missing');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_UNSELECT_CARD){if(p.can_finish){core.duelSetResponse(duel,{type:R.SELECT_UNSELECT_CARD,index:null});}else{const index=p.select_cards.findIndex(c=>c.code===material);if(index<0)throw Error('Material selection missing');core.duelSetResponse(duel,{type:R.SELECT_UNSELECT_CARD,index});}}
    else if(p.type===M.SELECT_CHAIN)core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:p.forced?0:null});
    else if(p.type===M.SELECT_PLACE){let location=L.MZONE,sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);if(sequence===undefined){location=L.SZONE;sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);}core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location,sequence}]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }
   if(!done)throw Error('Step limit');
  }catch(e){failure=e.message}finally{core.destroyDuel(duel)}
  results.push({...test,failure,activated,trace,logs});console.log(`${failure?'FAIL':'PASS'} ${JSON.stringify(test)}${failure?': '+failure:''}`);
 }
 fs.writeFileSync(path.join(ROOT,`output/fresh-ccg-september/nephthys-sacred-feather${process.argv.includes('--old-relation')?'-old-relation':process.argv.includes('--deck-api')?'-deck-api':process.argv.includes('--old-deck-release')?'-old-deck-release':process.argv.includes('--ordinary-send')?'-ordinary-send':''}.json`),JSON.stringify({engine:'public OCGCore with existing Sacred Feather; neutral Ritual plus actual EVENT_RELEASE fixture on materials; not native Omega',adapter:process.argv.includes('--deck-api')?'In-memory Deck branch uses ReleaseRitualMaterial(mat,true) instead of Release; not production or native Omega proof':null,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(r=>r.failure))process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1});
