'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/fresh-ccg-september'),source=path.join(root,'public/CCG Downloads/CCG_Scripts/c215034223.lua');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const plans=[{control:null,failed:[]},{control:'any-set',failed:[{wrongSet:true}]},{control:'any-type',failed:[{notPendulum:true}]},{control:'no-placement',failed:[{}]},{control:'old-cost',failed:[{noCost:true}]}].map(p=>({...p,h:'placement',artifact:'placement',cases:4}));
plans.push(...[{control:null,failed:[]},{control:'one-only',failed:[{two:true}]},{control:'any-position',failed:[{extra:true,facedown:true}]}].map(p=>({...p,h:'sources',artifact:'sources',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'one-only',failed:[{mixed:true}]},{control:'no-placement',failed:[{mixed:true},{oneOccupied:true}]}].map(p=>({...p,h:'zones',artifact:'zones',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'no-equip',failed:[{}]},{control:'any-attribute',failed:[{wrongAttribute:true}]}].map(p=>({...p,h:'equip',artifact:'equip',cases:5})));
plans.push(...[{control:null,failed:[]},{control:'no-equip',failed:[{arm:215921734},{arm:248788543},{arm:255832330}]},{control:'no-granted-effects',failed:[{arm:215921734},{arm:248788543},{arm:255832330}]}].map(p=>({...p,h:'arms',artifact:'arms',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'flat-count',failed:[{arm:248788543},{arm:255832330}]},{control:'any-controller',failed:[{arm:248788543,opponentEquip:true},{arm:255832330,opponentEquip:true}]}].map(p=>({...p,h:'equip_count',artifact:'equip-count',cases:4})));
plans.push(...[{control:null,failed:[]},{control:'frozen-count',failed:[{arm:248788543},{arm:255832330}]},{control:'no-removal',failed:[{arm:248788543},{arm:255832330}]}].map(p=>({...p,h:'equip_removal',artifact:'equip-removal',cases:2})));
plans.push(...[{control:null,failed:[]},{control:'no-protection',failed:[{arm:238136421}]},{control:'no-removal',failed:[{arm:238136421,remove:true}]}].map(p=>({...p,h:'target_protection',artifact:'target-protection',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'no-pierce',failed:[{arm:215921734}]},{control:'no-replacement',failed:[{arm:248788543}]}].map(p=>({...p,h:'battle',artifact:'battle',cases:3})));
plans.push(...[{control:null,failed:[]},{control:'no-replacement',failed:[{arm:255832330},{arm:255832330,send:true},{arm:255832330,decline:true},{arm:255832330,send:true,decline:true}]},{control:'any-controller',failed:[{arm:255832330,own:true},{arm:255832330,own:true,send:true}]}].map(p=>({...p,h:'shield_replacement',artifact:'shield-replacement',cases:6})));
plans.push(...[{control:null,failed:[]},{control:'no-replacement',failed:[{arm:255832330,banish:true},{arm:255832330,hand:true},{arm:255832330,deck:true}]}].map(p=>({...p,h:'shield_edge',artifact:'shield-edge',cases:3})));
plans.push(...plans.filter(p=>['arms','target_protection','battle','shield_replacement','shield_edge'].includes(p.h)).map(p=>({...p,args:['--canonical-arms'],artifact:p.artifact+'-canonical'})));
const database=path.join(out,'candidate-CCG_v1.db'),databaseHash=hash(database);
const sourceHash=hash(source),runs=[];
for(const plan of plans){
 const harness=path.join(__dirname,'fresh_talismandrake_united_'+plan.h+'.cjs'),harnessHash=hash(harness);
 const started=Date.now(),args=['--no-warnings',harness,...(plan.args||[]),...(plan.control?['--'+plan.control]:[])];let status=0;
 try{execFileSync(process.execPath,args,{cwd:root,timeout:30000,stdio:'pipe'});}catch(e){assert.equal(e.signal,null,'Timed out/terminated child');status=e.status;}
 const file=path.join(out,'talismandrake-united-'+(plan.artifact||plan.h)+(plan.control?'-'+plan.control:'')+'.json');assert(fs.statSync(file).mtimeMs>=started-2000,'Stale result');const result=JSON.parse(fs.readFileSync(file,'utf8'));
 assert.equal(result.script_sha256,sourceHash);if(plan.support)assert.equal(result.supporting_script_sha256,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c'+plan.support+'.lua')));if(plan.args&&plan.args.includes('--official'))assert.equal(result.supporting_script_sha256,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c246380598.lua')));if(plan.args?.includes('--canonical-arms')){assert.equal(result.canonical_arms,true);assert.deepEqual(Object.keys(result.supporting_scripts_sha256).sort(),[...new Set(result.results.map(r=>String(r.test.arm)))].sort());for(const [code,sha] of Object.entries(result.supporting_scripts_sha256))assert.equal(sha,hash(path.join(root,'public/CCG Downloads/CCG_Scripts/c'+code+'.lua')));}assert.equal(result.results.length,plan.cases);assert.deepEqual(result.results.filter(r=>r.failure).map(r=>r.test),plan.failed);assert.equal(status,plan.failed.length?1:0);assert.equal(hash(source),sourceHash);assert.equal(hash(harness),harnessHash);
 assert.equal(hash(database),databaseHash);runs.push({harness:plan.h,harness_sha256:harnessHash,control:plan.control,status,expected_failures:plan.failed,artifact_sha256:hash(file)});
}
fs.writeFileSync(path.join(out,'talismandrake-united-batch.json'),JSON.stringify({scope:'United fullsource native discardcost and DeckPendulum placement4; no adapters/bypass; Sources3 tested; Mixedsources/zones3 tested; SuppressorEquip5 tested; OtherArms stats3 tested; DynamicEquip count4 tested; Dynamic removal2 tested; Suppressor actual own/opponent targeting and removal3 tested; Halberd piercing/Sabre battle replacement3 tested; Shield opponent/own destroy/sendGY accepted/declined6 tested; Shield banish/hand/Deck replacement3 tested; 18 additional fullcanonical Arms integration cases; neutral generic Fusion recipient; remainingeffects/native Omega open',script_sha256:sourceHash,candidate_database_sha256:databaseHash,runs},null,2)+'\n');console.log(JSON.stringify({runs:runs.length,baseline_cases:57,status:'PASS'}));
