'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=211086520,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--legacy-oath')?'legacy-oath':process.argv.includes('--plain-count')?'plain-count':process.argv.includes('--ignore-search-success')?'ignore-search-success':process.argv.includes('--no-count')?'no-count':process.argv.includes('--no-discard')?'no-discard':null;
 for(const test of [{},{selfDiscard:true},{wrongSet:true},{spell:true},{absent:true},{count:true},{blocked:true},{negation:"activation"},{negation:"effect"}]){
  const targetCode=lab;
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:test.spell?2:33,setcodes:test.wrongSet?[]:[0x39e2]}],[filler,{...base,code:filler}],[spellCost,{...base,code:spellCost,type:2}]]);
  cards.set(recipient,{...base,code:recipient,type:33});
  const reader=name=>{
   if(test.negation&&name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_CHAINING) e:SetCountLimit(1) e:SetCondition(function(e,tp,eg,ep,ev,re) return re:GetHandler():IsCode('+boss+') end) e:SetOperation(function(e,tp,eg,ep,ev) Duel.'+(test.negation==='activation'?'NegateActivation':'NegateEffect')+'(ev) end) c:RegisterEffect(e) end';
   if(test.blocked&&name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_CHAINING) e:SetCountLimit(1) e:SetCondition(function(e,tp,eg,ep,ev,re) return re:GetHandler():IsCode('+boss+') end) e:SetOperation(function(e,tp) local g=Duel.GetMatchingGroup(Card.IsCode,tp,0,LOCATION_DECK,nil,'+lab+') Duel.Remove(g,POS_FACEUP,REASON_EFFECT) end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='plain-count')lua=lua.replace('id+EFFECT_COUNT_CODE_OATH','id');if(control==='ignore-search-success')lua=lua.replace('if #g>0 and Duel.SendtoHand(g,nil,REASON_EFFECT)>0 then','Duel.SendtoHand(g,nil,REASON_EFFECT)\n if true then');if(control==='no-count')lua=lua.replace('e1:SetCountLimit(1,id+EFFECT_COUNT_CODE_OATH)','do end');if(control==='no-discard')lua=lua.replace('Duel.DiscardHand(tp,Card.IsDiscardable,1,1,REASON_EFFECT+REASON_DISCARD)','do end');
    if(!process.argv.includes('--legacy-oath'))lua=lua.replace('e1:SetCountLimit(1,id+EFFECT_COUNT_CODE_OATH)','e1:SetCountLimit(1,id,1)');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,placementStarted=false,placementFinished=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence:0,position});
   add(boss,L.HAND);if(test.blocked||test.negation)add(recipient,L.MZONE,1,P.FACEUP_ATTACK);if(test.negation){add(boss,L.HAND);add(lab,L.DECK);}if(test.count){add(boss,L.HAND);if(test.blocked||test.negation)add(recipient,L.MZONE,1,P.FACEUP_ATTACK);if(test.negation){add(boss,L.HAND);add(lab,L.DECK);}add(lab,L.DECK);}if(!test.selfDiscard)add(spellCost,L.HAND);if(!test.absent)add(lab,L.DECK);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(!activated){const index=p.activates.findIndex(c=>c.code===boss);assert.equal(index>=0,!test.wrongSet&&!test.spell&&!test.absent,'Search availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(test.negation){assert(trace.some(m=>m.type===M.CHAINING&&m.code===recipient&&m.chain_size===2),'Actual opponent negation CL2');assert.equal(query(L.DECK).filter(c=>c.code===lab).length,2,'No search under negation');assert(query(L.HAND).some(c=>c.code===spellCost),'No discard under negation');assert.equal(query(L.HAND).filter(c=>c.code===boss).length,1,'Second source retained');assert.equal(p.activates.some(c=>c.code===boss),test.negation==='activation','Activation oath refund versus effect-negation consumption');done=true;continue;}if(test.blocked){assert(trace.some(m=>m.type===M.CHAINING&&m.code===recipient&&m.chain_size===2),'Actual opponent interruption CL2');const lost=query(L.REMOVED).find(c=>c.code===lab);assert(lost&&(lost.reason&0x40),'Only legal Deck target actually removed by chained effect');assert(query(L.HAND).some(c=>c.code===spellCost),'Other Hand card retained when search fails');assert(!query(L.GRAVE).some(c=>c.code===spellCost),'No discard after failed search');done=true;continue;}const search=trace.findIndex(m=>m.type===M.MOVE&&m.card===lab&&m.from.location===L.DECK&&m.to.location===L.HAND);assert(search>=0,'Actual Deck-to-Hand search');const code=test.selfDiscard?lab:spellCost;const discard=query(L.GRAVE).find(c=>c.code===code);assert(discard,'Actual card discarded');assert(discard.reason&0x40,'Discard as effect');assert(discard.reason&0x4000,'Native discard reason');assert(!(discard.reason&0x80),'Discard is not cost');const departure=trace.findIndex(m=>m.type===M.MOVE&&m.card===code&&m.from.location===L.HAND&&m.to.location===L.GRAVE);assert(departure>search,'Discard follows search');if(!test.selfDiscard)assert(query(L.HAND).some(c=>c.code===lab),'Searched Monster retained');if(test.count){assert.equal(query(L.HAND).filter(c=>c.code===boss).length,1,'Second copy retained Hand');assert(query(L.DECK).some(c=>c.code===lab),'Second legal target retained Deck');if(turn===1)assert(!p.activates.some(c=>c.code===boss),'Shared activation limit blocks second copy');if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}assert(p.activates.some(c=>c.code===boss),'Activation available next own turn');}done=true;}
    else if(p.type===M.SELECT_CARD){const fromDeck=p.selects.some(c=>c.location===L.DECK);const wanted=fromDeck||test.selfDiscard?lab:spellCost;const index=p.selects.findIndex(c=>c.code===wanted);assert(index>=0,'Actual search/discard choice');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.SZONE,sequence}]});}
    else if(p.type===M.SELECT_CHAIN){const index=(test.blocked||test.negation)&&p.player===1?p.selects.findIndex(c=>c.code===recipient):-1;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/recollection-search'+(control?'-'+control:'')+'.json'),JSON.stringify({adapter:process.argv.includes('--legacy-oath')?null:'In-memory source oath call translated from Omega packed id+0x10000000 to public SetCountLimit(1,id,1); production unchanged',engine:'Public OCGCore, full production Battle Preparation/candidate metadata; neutral cost and Deck targets. Actual archetype Monster search then effect discard; neutral targets; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
