'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210175845,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--partial-destruction')?'partial-destruction':process.argv.includes('--shared-effects')?'shared-effects':process.argv.includes('--no-revival')?'no-revival':null;
 for(const test of [{chain:3,integrated:true},{chain:3,integrated:true,loss:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:33,setcodes:test.wrongPartner?[]:[0x52f8]}],[filler,{...base,code:filler}],[spellCost,{...base,code:spellCost,type:0x20002}],[recipient,{...base,code:recipient,type:2}]]);
  const reader=name=>{
   if(test.chain&&name==='c'+recipient+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function() end) c:RegisterEffect(e) end';
   if(test.loss&&name==='c'+filler+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_FREE_CHAIN) e:SetCountLimit(1) e:SetOperation(function(e,tp) local c=Duel.GetMatchingGroup(Card.IsCode,tp,0,LOCATION_SZONE,nil,'+spellCost+'):GetFirst() if c then Duel.Destroy(c,REASON_EFFECT) end end) c:RegisterEffect(e) end';
   if(test.chain===3&&(name==='c'+lab+'.lua'||name==='c'+filler+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_QUICK_O) e:SetRange(LOCATION_MZONE) e:SetCode(EVENT_FREE_CHAIN) e:SetCountLimit(1) e:SetOperation(function() end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='partial-destruction')lua=lua.replace('if #g<e:GetLabel() then return end','if #g<e:GetLabel() then e:SetLabel(#g) end');if(control==='shared-effects')lua=lua.replace('e2:SetCountLimit(1,id+100)','e2:SetCountLimit(1,id)');if(control==='no-revival')lua=lua.replace('Duel.SpecialSummon(c,0,tp,tp,false,false,POS_FACEUP)','do end');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,chainStarted=false,revivalActivated=false,costSeen=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   if(test.chain)add(recipient,L.HAND);add(filler,L.MZONE,0,P.FACEUP_ATTACK,2);add(boss,L.MZONE,0,P.FACEUP_ATTACK);if(!test.absentPartner)add(lab,L.MZONE,0,test.facedownPartner?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK,1);if(!test.noOpponent){add(filler,L.MZONE,1,P.FACEUP_ATTACK);add(spellCost,L.SZONE,1,P.FACEUP_ATTACK);if(test.chain===3)add(filler,L.MZONE,1,P.FACEUP_ATTACK,1);}for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=(location,controller=0)=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(test.chain&&!chainStarted){const index=p.activates.findIndex(c=>c.code===recipient);assert(index>=0,'Neutral chain starter available');chainStarted=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(!activated){const index=p.activates.findIndex(c=>c.code===boss);assert.equal(index>=0,!test.absentPartner&&!test.wrongPartner&&!test.facedownPartner&&!test.noOpponent,'Quick destruction availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(trace.some(m=>m.type===M.CHAINING&&m.code===boss&&m.location===L.MZONE&&m.chain_size===(test.chain||1)),'Native Principality chain position');assert(costSeen,'Source paid actual GY COST before revival');assert(revivalActivated,'Actual revival selected');assert(query(L.MZONE).some(c=>c.code===boss),'Same source revived before destruction resolution');assert(!query(L.GRAVE).some(c=>c.code===boss),'Revived source left GY');assert(trace.some(m=>m.type===M.CHAINING&&m.code===boss&&m.location===L.GRAVE&&m.chain_size===5),'Native revival CL5');const destroyed=query(L.GRAVE,1).filter(c=>c.code===filler||c.code===spellCost);assert.equal(destroyed.length,test.loss?1:test.chain||1,'Exact opponent destruction count');assert(destroyed[0].reason&0x40,'Actual effect reason');assert(destroyed[0].reason&1,'Actual destruction reason');if(test.loss){assert.equal(query(L.MZONE,1).length,2,'Two opponent Monsters retained after target loss');assert.equal(query(L.SZONE,1).length,0,'Neutral CL4 actually destroyed opponent Spell');}assert(query(L.MZONE).some(c=>c.code===lab),'Other Scarstech retained');done=true;}
    else if(p.type===M.SELECT_CARD){assert(!test.loss,'No partial destruction selection after target loss');assert.equal(p.min,test.chain||1,'Exact chain selection minimum');assert.equal(p.max,test.chain||1,'Exact chain selection maximum');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:Array.from({length:test.chain||1},(_,i)=>i)});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const location=revivalActivated?L.MZONE:L.SZONE;const offset=revivalActivated?0:8;const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(offset+i)))===0);assert(sequence!==undefined,'Legal native placement');core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location,sequence}]});}
    else if(p.type===M.SELECT_CHAIN){let index=-1;if(chainStarted&&p.player===0&&!revivalActivated){const current=trace.filter(m=>m.type===M.CHAINING).length;if(current===3){const source=query(L.GRAVE).find(c=>c.code===boss);assert(source&&(source.reason&0x80),'Production destruction sends source GY as COST during chain building');costSeen=true;}const wanted=current===1?lab:current===2?boss:current===3?filler:boss;const location=current>=4?L.GRAVE:L.MZONE;index=p.selects.findIndex(c=>c.code===wanted&&c.location===location);assert(index>=0,'Integrated next response available at CL'+(current+1));if(current===2)activated=true;if(current===4)revivalActivated=true;}core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/scarstech-principality-integrated'+(control?'-'+control:'')+'.json'),JSON.stringify({engine:'Public OCGCore; full production Principality/candidate metadata, neutral partner/opponent cards. Actual production destruction GY cost, native CL5 revival, then CL3 destruction; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
