'use strict';
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const ROOT=path.resolve(__dirname,'..'),CUSTOM=path.join(ROOT,'public/CCG Downloads/CCG_Scripts'),OMEGA=path.join(ROOT,'tmp/omega_scripts');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=238276252,victim=900000931,small=900000932,filler=900000933,setup=900000934,search=900000935,fill=900000936,wind=63356631,spirit=59822133,msg=132276252,results=[];
 const tests=[{},{handVictim:true},{mixed:true},{full:true},{oneSpace:true,handVictim:true},{wrongLevel:true},{oneSmall:true},{spirit:true},{protected:true},{chainFill:true},{search:true},{search:true,grave:true},{search:true,removed:true},{search:true,wind:true},{search:true,faceDown:true},{search:true,nonRitual:true},{search:true,sameEvent:true},{search:true,decline:true}];
 for(const test of tests){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:33,level:2,attribute:8,race:32n,attack:300,defense:200,lscale:0,rscale:0,link_marker:0};
  const target=test.wind?wind:search,legalActivation=!test.full&&!test.oneSpace&&!test.wrongLevel&&!test.oneSmall&&!test.spirit,legalSearch=test.search&&!test.faceDown&&!test.nonRitual&&!test.sameEvent&&!test.decline;
  const cards=new Map([[boss,{...base,code:boss,setcodes:[0x11f],type:0x10002,level:0}],[victim,{...base,code:victim,setcodes:[0x11f],level:test.wrongLevel?7:8,type:test.search&&!test.nonRitual?0xa1:33}],[small,{...base,code:small,setcodes:[0x11f]}],[filler,{...base,code:filler}],[setup,{...base,code:setup,type:2,level:0}],[search,{...base,code:search,setcodes:[0x11f],type:2,level:0}],[wind,{...base,code:wind,type:4,level:0}],[spirit,{...base,code:spirit,type:0x2021,level:9,race:8192n}],[fill,{...base,code:fill,type:0x10002,level:0}]]);
  const reader=name=>{
   if(name===`c${fill}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetCondition(function() return Duel.GetCurrentChain()>0 end) e:SetOperation(function(e,tp) local g=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${filler}) Duel.SpecialSummon(g,0,tp,tp,false,false,POS_FACEUP) end) c:RegisterEffect(e) end`;
   if(name===`c${small}.lua`)return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F) e:SetCode(EVENT_SPSUMMON_SUCCESS) e:SetOperation(function(e,tp) Duel.Damage(tp,777,REASON_EFFECT) end) c:RegisterEffect(e) local e2=Effect.CreateEffect(c) e2:SetType(EFFECT_TYPE_IGNITION) e2:SetRange(LOCATION_MZONE) e2:SetOperation(function(e,tp) Duel.Damage(tp,111,REASON_EFFECT) end) c:RegisterEffect(e2) end';
   if(name===`c${setup}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function(e,tp) local g=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_MZONE,0,nil,${victim}) ${test.sameEvent?`g:Merge(Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_SZONE,0,nil,${boss}))`:''} Duel.Destroy(g,REASON_EFFECT) end) c:RegisterEffect(e) end`;
   if(name===`c${victim}.lua`&&test.protected)return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_SINGLE) e:SetCode(EFFECT_INDESTRUCTABLE_EFFECT) e:SetValue(1) c:RegisterEffect(e) end';
   if([victim,filler,search,wind].some(id=>name===`c${id}.lua`))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(CUSTOM,name),path.join(OMEGA,name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let source=fs.readFileSync(file,'utf8');if(name===`c${boss}.lua`){if(process.argv.includes('--no-negation'))source=source.replace('tc:RegisterEffect(e1,true)','--no negation').replace('tc:RegisterEffect(e2,true)','--no effect negation');if(process.argv.includes('--no-end-destruction'))source=source.replace('Duel.RegisterEffect(de,tp)','--no End Phase registration');if(process.argv.includes('--same-event'))source=source.replace('not eg:IsContains(e:GetHandler()) and ','');}return source;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,offered=false,done=false,turn=0,checked=false,filled=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,sequence=0,position=P.FACEUP_ATTACK)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   add(boss,test.search?(test.sameEvent?L.SZONE:L.GRAVE):L.HAND);add(victim,test.handVictim?L.HAND:L.MZONE);if(test.search){add(setup,L.HAND);add(target,test.removed||test.faceDown?L.REMOVED:test.grave?L.GRAVE:L.DECK,0,0,test.faceDown?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK);}else{add(small,L.HAND);if(!test.oneSmall)add(small,test.mixed?L.HAND:L.GRAVE);if(test.full||test.oneSpace)for(let i=1;i<5;i++)add(filler,L.MZONE,0,test.oneSpace?i-1:i);}for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);
   if(test.chainFill){add(fill,L.HAND);add(filler,L.MZONE,0,1);add(filler,L.MZONE,0,2);add(filler,L.HAND);add(filler,L.HAND);}if(test.spirit)add(spirit,L.MZONE,0,1);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.STATUS|Q.REASON,controller:0,location});
   for(let step=0;step<130&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));if(state===S.END)throw Error('Duel ended');if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){
     if(!activated){const index=p.activates.findIndex(c=>c.code===(test.search?setup:boss)&&c.location===L.HAND);if(!test.search&&!legalActivation){if(index>=0)throw Error('Illegal activation offered');done=true;continue;}if(index<0)throw Error('Activation unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if(test.search){if(query(L.HAND).some(c=>c?.code===target)!==!!legalSearch)throw Error('Search outcome mismatch');if(query(L.REMOVED).some(c=>c?.code===boss)!==!!legalSearch)throw Error('Search banish-cost outcome mismatch');if(offered!==(!test.faceDown&&!test.nonRitual&&!test.sameEvent))throw Error('GY trigger legality mismatch');done=true;}
     else if(test.chainFill){if(!filled||query(L.MZONE).filter(c=>c?.code===filler).length!==4||query(L.MZONE).some(c=>c?.code===small)||!query(L.GRAVE).some(c=>c?.code===victim&&(c.reason&1)))throw Error('Chained zone-fill should allow destruction but prevent two Summons');done=true;}
     else if(test.protected){if(!query(L.MZONE).some(c=>c?.code===victim)||query(L.MZONE).some(c=>c?.code===small))throw Error('Summon proceeded despite destruction prevention');done=true;}
     else if(turn>=2){if(query(L.MZONE).some(c=>c?.code===small))throw Error('Summoned monsters survived End Phase');const sg=query(L.GRAVE).filter(c=>c?.code===small);if(sg.length!==2||sg.some(c=>(c.reason&1)===0||(c.reason&0x40)===0))throw Error('End Phase actual destruction mismatch');done=true;}
     else{if(!checked){const sg=query(L.MZONE).filter(c=>c?.code===small);if(sg.length!==2||sg.some(c=>(c.status&1)===0))throw Error('Two actual disabled Summons missing');if(trace.some(m=>m.type===M.DAMAGE&&m.amount===777))throw Error('Summoned trigger effects not negated');if(!query(L.GRAVE).some(c=>c?.code===victim&&(c.reason&1)&&(c.reason&0x40)))throw Error('Victim not actually destroyed');checked=true;const index=p.activates.findIndex(c=>c.code===small);if(index<0)throw Error('Ignition probe unavailable');core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(trace.some(m=>m.type===M.DAMAGE&&m.amount===111))throw Error('Actual ignition probe was not negated');core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});}
    }else if(p.type===M.SELECT_CHAIN){const fi=p.selects.findIndex(c=>c.code===fill);if(fi>=0&&!filled){filled=true;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:fi});continue;}const index=p.selects.findIndex(c=>c.code===boss&&String(c.description)===String(msg*16+1));if(index>=0)offered=true;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?(test.decline?null:index):p.forced?0:null});}
    else if(p.type===M.SELECT_EFFECTYN){offered=true;core.duelSetResponse(duel,{type:R.SELECT_EFFECTYN,yes:!test.decline});}
    else if(p.type===M.SELECT_CARD){const wanted=p.selects.some(c=>c.code===victim)?victim:test.search?target:small;const indices=p.selects.map((c,i)=>c.code===wanted?i:-1).filter(i=>i>=0).slice(0,wanted===small?2:1);core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:indices});}
    else if(p.type===M.SELECT_PLACE){let location=L.MZONE,sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);if(sequence===undefined){location=L.SZONE;sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);}core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location,sequence}]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }if(!done)throw Error('Step limit');
  }catch(e){failure=e.message}finally{core.destroyDuel(duel)}
  results.push({...test,failure,offered,trace,logs});console.log(`${failure?'FAIL':'PASS'} ${JSON.stringify(test)}${failure?': '+failure:''}`);
 }
 const control=['--no-negation','--no-end-destruction','--same-event'].find(flag=>process.argv.includes(flag));
 fs.writeFileSync(path.join(ROOT,`output/fresh-ccg-september/nephthys-prayer${control?control.slice(1):''}.json`),JSON.stringify({engine:'Public OCGCore with complete Prayer production Lua; neutral Level 8 victim/search targets and Level 2 monsters with actual Summon trigger/ignition fixtures; native Omega untested',control:control||null,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(r=>r.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1});
