'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210696007,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--ignore-capacity')?'ignore-capacity':process.argv.includes('--separate-effects')?'separate-effects':process.argv.includes('--no-permission')?'no-permission':process.argv.includes('--allow-facedown')?'allow-facedown':null;
 for(const test of [{},{quickplay:true},{normalSpell:true},{wrongSet:true},{monster:true},{facedown:true},{selfTarget:true},{three:true},{shared:true},{limited:true},{full:true}]){
  const targetCode=test.selfTarget?boss:lab;
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:test.monster?33:test.quickplay?0x10002:test.normalSpell?2:4,level:test.monster?2:0,setcodes:test.wrongSet?[]:[0x9c9]}],[filler,{...base,code:filler}],[spellCost,{...base,code:spellCost,type:2}],[recipient,{...base,code:recipient,type:2,setcodes:[0x9c9]}]]);
  const reader=name=>{
   if(name==='c'+lab+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function(e,tp) Duel.Hint(HINT_NUMBER,tp,702) end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='constant.lua')lua=lua.replace(/(CHAININFO_TARGET_CARDS\s*=)0x40/,'$1 8').replace(/(EFFECT_QP_ACT_IN_SET_TURN\s*=)359/,'$1 19');if(name==='c'+boss+'.lua'){
    if(control==='ignore-capacity')lua=lua.replace('math.min(3,ft)','3');if(control==='separate-effects')lua=lua.replace('e2:SetCountLimit(1,id)','e2:SetCountLimit(1,id+100)');if(control==='no-permission')lua=lua.replace('tc:RegisterEffect(te)','do end');if(control==='allow-facedown')lua=lua.replace('c:IsFaceup() and c:IsSetCard(SET_GALACTICA)','c:IsSetCard(SET_GALACTICA)');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false,placementStarted=false,placementFinished=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   add(boss,L.SZONE);if(test.limited||test.full)for(let i=1;i<=(test.full?4:3);i++)add(spellCost,L.SZONE,0,P.FACEUP_ATTACK,i);if(test.shared){add(spellCost,L.GRAVE,0,P.FACEUP_ATTACK);add(recipient,L.DECK);}for(let i=0;i<(test.three||test.limited?3:1);i++)add(targetCode,L.REMOVED,0,test.facedown?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(!activated){const index=p.activates.findIndex(c=>c.code===boss);if(test.limited||test.full)assert.equal(query(L.SZONE).length,test.full?5:4,'Explicit occupied SZONE count before activation');assert.equal(index>=0,!test.wrongSet&&!test.monster&&!test.facedown&&!test.selfTarget&&!test.full,'Set effect availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(test.shared){assert(query(L.GRAVE).some(c=>c.code===boss),'Resolved source in GY');assert(query(L.GRAVE).some(c=>c.code===spellCost),'Legal second cost retained GY');assert(query(L.DECK).some(c=>c.code===recipient),'Legal Deck target retained');assert.equal(query(L.SZONE).filter(c=>c.code===lab).length,1,'Actual Set effect resolved');if(turn===1)assert(!p.activates.some(c=>c.code===boss&&c.location===L.GRAVE),'Set use blocks GY effect same turn');if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}assert(p.activates.some(c=>c.code===boss&&c.location===L.GRAVE),'GY effect available next own turn');done=true;continue;}if(!secondary){assert.equal(query(L.SZONE).filter(c=>c.code===lab).length,test.three?3:1,'Actual recovered cards Set');assert.equal(query(L.REMOVED).filter(c=>c.code===lab).length,test.limited?2:0,'Unselected cards remain banished');assert.equal(turn,1,'Still same turn');const index=p.activates.findIndex(c=>c.code===lab);assert(index>=0,'Recovered card can activate same turn');secondary=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(trace.some(m=>m.type===M.HINT&&String(m.hint)==='702'),'Recovered card actually resolved same turn');done=true;}
    else if(p.type===M.SELECT_CARD){if(test.limited)assert.equal(p.max,1,'Selection capped by one free SZONE');const indicies=p.selects.map((c,i)=>c.code===lab?i:-1).filter(i=>i>=0).slice(0,test.three?3:1);assert.equal(indicies.length,test.three?3:1,'Target selection');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.SZONE,sequence}]});}
    else if(p.type===M.SELECT_CHAIN)core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:p.forced?0:null});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/galataxian-battle-preparation-set'+(control?'-'+control:'')+'.json'),JSON.stringify({adapter:'In-memory pinned constant.lua CHAININFO_TARGET_CARDS mapped from 0x40 to public core enum8; EFFECT_QP_ACT_IN_SET_TURN from359 to19 per ProjectIgnis constant.lua; production unchanged',engine:'Public OCGCore, full production Battle Preparation/candidate metadata; neutral cost and Deck targets. Actual recovery Set and same-turn activation; no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
