'use strict';
const {sylvanCard}=require('./fresh_sylvan_metadata.cjs');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const ROOT=path.resolve(__dirname,'..'),CUSTOM=path.join(ROOT,'public/CCG Downloads/CCG_Scripts'),OMEGA=path.join(ROOT,'tmp/omega_scripts');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=238276573,greetings=238276575,plant=900000951,nonplant=900000952,spell=900000953,ally=900000954,setup=900000955,filler=900000956,loss=900000957,macro=30241314,msg=132276573,results=[];
 for(const test of [{},{nonplant:true},{spell:true},{normal:true},{special:true},{macro:true},{revive:true},{revive:true,self:true},{revive:true,ordinary:true},{revive:true,cost:true},{revive:true,lost:true},{greetings:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:33,level:2,attribute:4,race:1024n,attack:100,defense:200,lscale:0,rscale:0,link_marker:0},top=test.revive?boss:test.greetings?greetings:test.nonplant?nonplant:test.spell?spell:plant;
  const cards=new Map([[greetings,{...base,code:greetings,setcodes:[0x90],type:0x10002,level:0}],[boss,{...base,code:boss,setcodes:[0x90],level:3,attack:1900,defense:1900}],[plant,{...base,code:plant,setcodes:[0x90],level:6}],[nonplant,{...base,code:nonplant,race:1n,level:7}],[spell,{...base,code:spell,type:2,level:0}],[ally,{...base,code:ally,setcodes:[0x90]}],[setup,{...base,code:setup,type:2,level:0}],[filler,{...base,code:filler,race:1n}],[loss,{...base,code:loss,type:0x10002,level:0}],[macro,{...base,code:macro,type:0x20004,level:0}]]);
  cards.set(boss,sylvanCard(boss));
  cards.set(greetings,sylvanCard(greetings));
  const reader=name=>{
   if(name===`c${setup}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function(e,tp) local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_DECK,0,nil,${top}):GetFirst() Duel.MoveSequence(tc,SEQ_DECKTOP) ${test.revive?`Duel.ConfirmDecktop(tp,1) Duel.SendtoGrave(tc,${test.cost?'REASON_COST+REASON_REVEAL':test.ordinary?'REASON_EFFECT':'REASON_EFFECT+REASON_REVEAL'})`:test.special?`local c=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${boss}):GetFirst() Duel.SpecialSummon(c,0,tp,tp,false,false,POS_FACEUP)`:''} end) c:RegisterEffect(e) end`;
   if(name===`c${loss}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetCondition(function(e,tp) return Duel.GetCurrentChain()>0 and Duel.IsExistingMatchingCard(Card.IsCode,tp,LOCATION_GRAVE,0,1,nil,${boss}) end) e:SetOperation(function(e,tp) local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_GRAVE,0,nil,${ally}):GetFirst() Duel.Remove(tc,POS_FACEUP,REASON_EFFECT) end) c:RegisterEffect(e) end`;
   if([plant,nonplant,spell,ally,filler].some(id=>name===`c${id}.lua`))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(CUSTOM,name),path.join(OMEGA,name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let source=fs.readFileSync(file,'utf8');if(name===`c${boss}.lua`&&process.argv.includes('--no-relation'))source=source.replace('tc and tc:IsRelateToEffect(e)','tc');if(name==='ccg_sylvan.lua'&&process.argv.includes('--send-gated-level'))source=source.replace('return lv','return first and first:IsLocation(LOCATION_GRAVE) and lv or 0');return source;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,summoned=false,excavated=false,offered=false,lost=false,done=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position:P.FACEUP_ATTACK});
   add(setup,L.HAND);add(boss,test.revive?L.DECK:test.normal||test.special?L.HAND:L.MZONE);if(!test.revive)add(top,L.DECK);else if(!test.self)add(ally,L.GRAVE);if(test.greetings)add(ally,L.GRAVE);if(test.lost)add(loss,L.HAND);if(test.macro)add(macro,L.SZONE,1,2);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.LEVEL|Q.REASON,controller:0,location});
   for(let step=0;step<130&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));if(state===S.END)throw Error('Duel ended');if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){
     if(!activated){const index=p.activates.findIndex(c=>c.code===setup);if(index<0)throw Error('Setup unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if(test.normal&&!summoned){const index=p.summons.findIndex(c=>c.code===boss);if(index<0)throw Error('Normal Summon unavailable');summoned=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_SUMMON,index});continue;}
     if(test.revive){const legal=!test.ordinary&&!test.cost&&!test.lost;if(offered!==(!test.ordinary&&!test.cost))throw Error('Revival trigger legality mismatch');if(query(L.MZONE).some(c=>c?.code===(test.self?boss:ally))!==legal)throw Error('Actual targeted revival mismatch');if(test.lost&&(!lost||!query(L.REMOVED).some(c=>c?.code===ally)))throw Error('Actual chained target removal missing');done=true;}
     else if(test.greetings&&excavated){if(!query(L.GRAVE).some(c=>c?.code===greetings&&(c.reason&0x8000000)&&(c.reason&0x40))||!query(L.MZONE).some(c=>c?.code===ally)||query(L.MZONE).find(c=>c?.code===boss)?.level!==3)throw Error('Greetings forced excavation/send/recruitment mismatch');done=true;}
     else{const index=p.activates.findIndex(c=>c.code===boss&&String(c.description)===String(msg*16+1));if(!excavated){if(index<0)throw Error('Ignition unavailable');if((test.normal||test.special)&&(!offered||query(L.DECK).filter(Boolean).at(-1)?.code!==plant))throw Error('On-Summon actual top placement failed');excavated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(index>=0)throw Error('Soft once-per-turn failed');const rc=query(L.MZONE).find(c=>c?.code===boss);if(rc.level!==(test.nonplant||test.spell?3:6))throw Error('Actual Level change mismatch');if(test.nonplant||test.spell){if(query(L.DECK).filter(Boolean)[0]?.code!==top)throw Error('Non-Plant not moved to bottom');}else if(!query(test.macro?L.REMOVED:L.GRAVE).some(c=>c?.code===plant&&(c.reason&0x8000000)&&(c.reason&0x40)))throw Error('Plant excavation/reason mismatch');done=true;}
    }else if(p.type===M.SELECT_CHAIN){const gi=p.selects.findIndex(c=>c.code===greetings);if(gi>=0){core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:gi});continue;}const index=p.selects.findIndex(c=>c.code===boss&&String(c.description)===String(msg*16+(test.revive?2:0)));const li=p.selects.findIndex(c=>c.code===loss);if(li>=0&&!lost){lost=true;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:li});continue;}if(index>=0)offered=true;core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else if(p.type===M.SELECT_EFFECTYN){offered=true;core.duelSetResponse(duel,{type:R.SELECT_EFFECTYN,yes:true});}
    else if(p.type===M.SELECT_CARD){const index=p.selects.findIndex(c=>c.code===(test.greetings?ally:test.revive?(test.self?boss:ally):plant));if(index<0)throw Error('Target candidate missing');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_PLACE){let location=L.MZONE,sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);if(sequence===undefined){location=L.SZONE;sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);}core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location,sequence}]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }if(!done)throw Error('Step limit');
  }catch(e){failure=e.message}finally{core.destroyDuel(duel)}
  results.push({...test,failure,offered,trace,logs});console.log(`${failure?'FAIL':'PASS'} ${JSON.stringify(test)}${failure?': '+failure:''}`);
 }
 const control=['--no-relation','--send-gated-level'].find(flag=>process.argv.includes(flag));
 fs.writeFileSync(path.join(ROOT,`output/fresh-ccg-september/sylvan-goleaf${control?control.slice(1):''}.json`),JSON.stringify({engine:'Public OCGCore; complete Goleaf, official Macro Cosmos seeded face-up, neutral cards and actual setup/excavation/Summon/chain-removal fixture Spells; no core/helper adapter; native Omega untested',control:control||null,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(r=>r.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1});
