 'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..'),boss=213266433,attacker=900001220,target=900001221,filler=900001222;
async function main(){const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,SelectBattleCMDAction:B}=mod;const core=await mod.default({sync:true,print(){},printErr(){}}),results=[],control=['no-extra','any-set','any-target'].find(c=>process.argv.includes('--'+c));
for(const test of [{},{faceupThird:true},{wrongSet:true},{firstFaceup:true},{noSource:true}]){const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:4,attribute:2,race:64n,attack:3000,defense:1000,lscale:0,rscale:0,link_marker:0};const cards=new Map([[boss,candidateCard(boss)],[attacker,{...base,code:attacker,setcodes:test.wrongSet?[]:[0x813]}],[target,{...base,code:target,attack:1000}],[filler,{...base,code:filler,type:2}]]);
const reader=name=>{if([attacker,target,filler].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';const f=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));assert(f);let lua=fs.readFileSync(f,'utf8');if(name==='c'+boss+'.lua'){if(control==='no-extra')lua=lua.replace('ac:RegisterEffect(e1)','do end');if(control==='any-set')lua=lua.replace('ac:IsSetCard(SET_FRUTE)','true');if(control==='any-target')lua=lua.replace('if not s.fddef(c) then return true end','if false then return true end');}return lua;};
const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});let failure=null,done=false,turn=0,attacks=0;
try{for(const n of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,n,reader(n));const add=(code,location,player=0,sequence=0,position=P.FACEUP_ATTACK)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});if(!test.noSource)add(boss,L.MZONE);add(attacker,L.MZONE,0,1);for(let i=0;i<3;i++)add(target,L.MZONE,1,i,(test.faceupThird&&i===2)||(test.firstFaceup&&i===0)?P.FACEUP_ATTACK:P.FACEDOWN_DEFENSE);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
for(let step=0;step<400&&!done;step++){const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join(';'));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);if(p.type===M.SELECT_IDLECMD)core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:turn===3?A.TO_BP:A.TO_EP,index:0});else if(p.type===M.SELECT_BATTLECMD){assert.equal(turn,3);const index=p.attacks.findIndex(c=>c.code===attacker);if(index>=0){assert(attacks<4,'Unexpected further attack');attacks++;core.duelSetResponse(duel,{type:R.SELECT_BATTLECMD,action:B.SELECT_BATTLE,index});}else{assert.equal(attacks,test.wrongSet||test.firstFaceup||test.noSource?1:test.faceupThird?2:3,'Attack all facedown defenders once each');done=true;}}else if(p.type===M.SELECT_CARD){if(test.faceupThird&&attacks>1)assert(!p.selects.some(c=>c.sequence===2),'Extra attack excludes faceup defender');const index=p.selects.findIndex(c=>c.sequence===attacks-1);assert(index>=0,'Next unique battle target');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}else if(p.type===M.SELECT_CHAIN)core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:p.forced?0:null});else if(p.type===M.SELECT_YESNO)core.duelSetResponse(duel,{type:R.SELECT_YESNO,yes:true});else throw Error('Unhandled '+JSON.stringify(p));}assert(done,'Step limit');}catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,attacks,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));}
fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/hanging-frute-battle'+(control?'-'+control:'')+'.json'),JSON.stringify({scope:'Full source seeded field, neutral Frute attacker actual ownturn3 attacks unique seeded defenders; no API adapters. No proper Ritual/monster-survival repeat edge/native Omega certification',script_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,'public/CCG Downloads/CCG_Scripts/c'+boss+'.lua'))).digest('hex'),results},(_,v)=>typeof v==='bigint'?String(v):v,2)+String.fromCharCode(10));if(results.some(r=>r.failure))process.exitCode=1;}
main().catch(e=>{console.error(e);process.exitCode=1;});
