'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{candidateCard}=require('./fresh_candidate_card.cjs');
const ROOT=path.resolve(__dirname,'..');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=210366076,lab=900001191,filler=900001192,spellCost=900001193,recipient=900001194,results=[];
 const control=process.argv.includes('--early-zone')?'early-zone':process.argv.includes('--no-count')?'no-count':process.argv.includes('--no-cost')?'no-cost':process.argv.includes('--allow-facedown')?'allow-facedown':process.argv.includes('--no-type')?'no-type':process.argv.includes('--any-continuous')?'any-continuous':process.argv.includes('--any-trap')?'any-trap':null;
 for(const test of [{},{grave:true},{removed:true},{facedown:true},{wrongRace:true},{lowLevel:true},{costFacedown:true},{costSpell:true},{normalTrap:true},{count:true},{fullSet:true},{fullHand:true}]){
  const logs=[],trace=[],base={alias:0,setcodes:[],type:17,level:2,attribute:1,race:1n,attack:100,defense:100,lscale:0,rscale:0,link_marker:0};
  const cards=new Map([[boss,candidateCard(boss)],[lab,{...base,code:lab,type:33,level:test.lowLevel?4:5,race:test.wrongRace?1n:16n}],[filler,{...base,code:filler}]]);
  cards.set(spellCost,{...base,code:spellCost,type:test.costSpell?0x20002:test.normalTrap?4:0x20004});cards.set(recipient,{...base,code:recipient});
  const reader=name=>{
   if(name==='c'+spellCost+'.lua')return 'local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_IGNITION) e:SetRange(LOCATION_GRAVE) e:SetOperation(function(e,tp) local c=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_SZONE,0,nil,'+lab+'):GetFirst() if c and c:IsType(TYPE_TRAP) and c:IsType(TYPE_CONTINUOUS) and not c:IsType(TYPE_MONSTER) then Duel.Hint(HINT_NUMBER,tp,701) end end) c:RegisterEffect(e) end';
   if([lab,filler,spellCost,recipient].some(c=>name==='c'+c+'.lua'))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=[path.join(ROOT,'public/CCG Downloads/CCG_Scripts',name),path.join(ROOT,'tmp/omega_scripts',name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let lua=fs.readFileSync(file,'utf8');if(name==='c'+boss+'.lua'){
    if(control==='early-zone')lua=lua.replace('or Duel.IsExistingMatchingCard(s.costfilter,tp,LOCATION_SZONE,0,1,nil)','');if(control==='no-count')lua=lua.replace('e1:SetCountLimit(1,id)','do end');if(control==='any-continuous')lua=lua.replace('c:IsType(TYPE_TRAP) and c:IsType(TYPE_CONTINUOUS)','c:IsType(TYPE_CONTINUOUS)');if(control==='any-trap')lua=lua.replace('c:IsType(TYPE_TRAP) and c:IsType(TYPE_CONTINUOUS)','c:IsType(TYPE_TRAP)');if(control==='no-cost')lua=lua.replace('Duel.SendtoGrave(tc,REASON_COST)','do end');if(control==='allow-facedown')lua=lua.replace('(c:IsLocation(LOCATION_DECK+LOCATION_GRAVE) or c:IsFaceup())','true');if(control==='no-type')lua=lua.replace('tc:RegisterEffect(e1)','do end');
   }return lua;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:code=>cards.get(code),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,done=false,turn=0,secondary=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,position=P.FACEDOWN_DEFENSE,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position});
   add(boss,test.fullSet?L.SZONE:L.HAND);if(test.fullSet||test.fullHand)for(let i=test.fullSet?2:1;i<5;i++)add(spellCost,L.SZONE,0,P.FACEUP_ATTACK,i);if(test.count){add(boss,L.HAND);add(lab,L.DECK);}add(spellCost,L.SZONE,0,test.costFacedown?P.FACEDOWN_DEFENSE:P.FACEUP_ATTACK,test.fullSet?1:0);add(lab,test.grave?L.GRAVE:test.removed||test.facedown?L.REMOVED:L.DECK,0,test.facedown?P.FACEDOWN_DEFENSE:test.removed||test.grave?P.FACEUP_ATTACK:P.FACEDOWN_DEFENSE);for(const player of [0,1])for(let i=0;i<8;i++)add(filler,L.DECK,player);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location}).filter(Boolean);
   for(let step=0;step<260&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));assert(state!==S.END);if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(!activated){if(test.fullSet||test.fullHand)assert.equal(query(L.SZONE).length,5,'All five SZONE slots occupied before activation');const index=p.activates.findIndex(c=>c.code===boss);assert.equal(index>=0,!test.facedown&&!test.wrongRace&&!test.lowLevel&&!test.costFacedown&&!test.costSpell&&!test.normalTrap&&!test.fullHand,'Placement availability');if(index<0){done=true;continue;}activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(query(L.SZONE).some(c=>c.code===lab),'Actual Zombie placement');const cost=query(L.GRAVE).find(c=>c.code===spellCost);assert(cost,'Continuous Trap sent to GY');assert(cost.reason&0x80,'Actual cost reason');if(!secondary){const index=p.activates.findIndex(c=>c.code===spellCost);assert(index>=0,'Native type probe available');secondary=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}assert(trace.some(m=>m.type===M.HINT&&String(m.hint)==='701'),'Native Continuous Trap type conversion');if(test.count){assert.equal(query(L.HAND).filter(c=>c.code===boss).length,1,'Second Meeting retained in hand');assert(query(L.DECK).some(c=>c.code===lab),'Second legal Zombie retained in Deck');if(turn===1)assert(!p.activates.some(c=>c.code===boss&&c.location===L.HAND),'Shared placement HOPT blocks second copy');if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}assert(p.activates.some(c=>c.code===boss&&c.location===L.HAND),'Placement renewed next own turn');}done=true;}
    else if(p.type===M.SELECT_CARD){const index=p.selects.findIndex(c=>c.code===spellCost||c.code===lab);assert(index>=0,'Lab selection');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.SZONE,sequence}]});}
    else if(p.type===M.SELECT_CHAIN)core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:p.forced?0:null});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }assert(done,'Step limit');
  }catch(e){failure=e.message;}finally{core.destroyDuel(duel);}results.push({test,failure,trace,logs});console.log((failure?'FAIL':'PASS')+' '+JSON.stringify(test)+(failure?': '+failure:''));
 }
 fs.writeFileSync(path.join(ROOT,'output/fresh-ccg-september/crewal-meeting-placement'+(control?'-'+control:'')+'.json'),JSON.stringify({engine:'Public OCGCore, full production Crewal Meeting/candidate metadata; neutral Zombie and cost Trap/native type probe. Actual placement/cost/type conversion, no native Omega certification.',control,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(c=>c.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1;});
