'use strict';
const {sylvanCard}=require('./fresh_sylvan_metadata.cjs');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const ROOT=path.resolve(__dirname,'..'),CUSTOM=path.join(ROOT,'public/CCG Downloads/CCG_Scripts'),OMEGA=path.join(ROOT,'tmp/omega_scripts');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=238276575,official=99641328,plant=900000971,sa=900000972,sb=900000973,nonplant=900000974,plain=900000975,setup=900000976,filler=900000977,ally=900000978,pp=900000979,np=900000980,results=[];
 for(const test of [{add:0},{add:1},{add:2},{add:2,forced:true},{short:true},{official:true},{snuff:true},{sage:true},{sage:true,plantTop:true},{sage:true,nonplantTop:true},{sage:true,hermit:true},{sage:true,hermit:true,plantTop:true},{sage:true,hermit:true,plantTop:true,macro:true},{sage:true,hermit:true,nonplantTop:true},{cherub:true},{cherub:true,two:true},{peas:true},{peas:true,normal:true},{marsh:true,normal:true},{marsh:true,normal:true,two:true},{guard:1},{guard:2},{guard:3},{guard:1,lotus:true},{guard:2,lotus:true},{guard:3,lotus:true},{send:true,sylvan:true},{send:true,sylvan:false}]){
  const source=test.hermit?25824484:test.lotus?73136204:test.guard?99429730:test.marsh?36046926:test.peas?63257623:test.cherub?10753491:test.sage?10530913:test.snuff?47741109:official;
  const logs=[],trace=[],base={alias:0,setcodes:[],type:33,level:2,attribute:4,race:1024n,attack:100,defense:200,lscale:0,rscale:0,link_marker:0},order=test.send?[]:test.guard?[boss,nonplant,plain].slice(0,test.guard):(test.cherub||test.marsh)&&test.two?[boss,nonplant]:test.plantTop?[plant]:test.nonplantTop?[nonplant]:test.official||test.snuff||test.sage||test.cherub||test.peas||test.marsh||test.guard?[boss]:test.short?[plant,sa,sb]:[plant,sa,sb,nonplant,test.forced?boss:plain];
  const cards=new Map([[boss,{...base,code:boss,setcodes:[0x90],type:0x10002,level:0}],[plant,{...base,code:plant}],[sa,{...base,code:sa,setcodes:[0x90],type:2,level:0}],[sb,{...base,code:sb,setcodes:[0x90],type:4,level:0}],[nonplant,{...base,code:nonplant,race:1n}],[plain,{...base,code:plain,type:2,level:0}],[setup,{...base,code:setup,type:2,level:0}],[filler,{...base,code:filler,race:1n}],[ally,{...base,code:ally,setcodes:[0x90]}],[pp,{...base,code:pp,type:2,level:0}],[np,{...base,code:np,type:2,level:0}]]);
  cards.set(source,{...base,code:source,setcodes:[0x90],defense:2000});
  cards.set(boss,sylvanCard(boss)); if(test.macro)cards.set(30241314,{...base,code:30241314,type:0x20004,level:0});
  if(test.send&&test.sylvan)cards.set(setup,{...cards.get(setup),setcodes:[0x90]});
  const reader=name=>{
   if(name===`c${setup}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetOperation(function(e,tp) ${order.slice().reverse().map(code=>`local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_DECK,0,nil,${code}):GetFirst() Duel.MoveSequence(tc,SEQ_DECKTOP)`).join(' ')} ${test.send?`local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${boss}):GetFirst() Duel.SendtoGrave(tc,REASON_EFFECT)`:test.cherub||(test.peas&&!test.normal)?`local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${source}):GetFirst() Duel.SpecialSummon(tc,0,tp,tp,false,false,POS_FACEUP)`:test.snuff?`local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${source}):GetFirst() Duel.SendtoGrave(tc,REASON_EFFECT)`:test.official?`local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_MZONE,0,nil,${source}):GetFirst() Duel.ChangePosition(tc,POS_FACEUP_ATTACK)`:''} end) c:RegisterEffect(e) end`;
   if([pp,np].some(code=>name===`c${code}.lua`)){const wanted=name===`c${pp}.lua`?plant:nonplant;return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetType(EFFECT_TYPE_ACTIVATE) e:SetCode(EVENT_FREE_CHAIN) e:SetTarget(function(e,tp,eg,ep,ev,re,r,rp,chk) if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0 and Duel.IsExistingMatchingCard(function(c) return c:IsCode(${wanted}) and c:IsCanBeSpecialSummoned(e,0,tp,false,false) end,tp,LOCATION_HAND,0,1,nil) end end) e:SetOperation(function(e,tp) local tc=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_HAND,0,nil,${wanted}):GetFirst() Duel.SpecialSummon(tc,0,tp,tp,false,false,POS_FACEUP) end) c:RegisterEffect(e) end`;}
   if([plant,sa,sb,nonplant,plain,filler,ally].some(id=>name===`c${id}.lua`))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';
   const file=name===`c${source}.lua`&&process.argv.includes('--original-official')?path.join(OMEGA,name):[path.join(CUSTOM,name),path.join(OMEGA,name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let luaSource=fs.readFileSync(file,'utf8');if(name===`c${boss}.lua`&&process.argv.includes('--no-lock'))luaSource=luaSource.replace('Duel.RegisterEffect(lock,tp)','--no lock');if(process.argv.includes('--old-setcode')&&[ `c${boss}.lua`,'ccg_sylvan.lua'].includes(name))luaSource=luaSource.replace(/0x90/g,'0xa6');if(name===`c${boss}.lua`&&process.argv.includes('--any-effect-source'))luaSource=luaSource.replace('re:GetHandler():IsSetCard(0x90)','true');if(name===`c${boss}.lua`&&process.argv.includes('--require-reveal'))luaSource=luaSource.replace('IsReason(REASON_EFFECT) and re','IsReason(REASON_EFFECT) and e:GetHandler():IsReason(REASON_REVEAL) and re');return luaSource;
  };
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,prepared=false,activated=false,plantSummoned=false,otherSummoned=false,done=false,turn=0,bottom=[];
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position:P.FACEUP_ATTACK});
   if(test.cherub||test.peas||test.marsh)add(source,L.HAND);else if(test.sage||test.guard)add(source,L.MZONE);else if(test.snuff)add(source,L.HAND);else if(!test.official)add(boss,L.HAND);else core.duelNewCard(duel,{team:0,duelist:0,code:source,controller:0,location:L.MZONE,sequence:0,position:P.FACEDOWN_DEFENSE});add(setup,L.HAND);for(const code of order)add(code,L.DECK);if(!test.short){add(pp,L.HAND);add(np,L.HAND);add(plant,L.HAND);add(nonplant,L.HAND);if(test.forced||test.official||test.snuff||test.sage||test.cherub||test.peas||test.marsh||test.guard||test.send)add(ally,L.GRAVE);}for(const player of [0,1])for(let i=0;i<(test.short&&player===0?0:8);i++)add(filler,L.DECK,player);if(test.lotus)for(let i=0;i<test.guard;i++)add(filler,L.MZONE,1,i);if(test.macro)add(30241314,L.SZONE,1,2);core.startDuel(duel);
   const query=location=>core.duelQueryLocation(duel,{flags:Q.CODE|Q.REASON,controller:0,location});
   for(let step=0;step<160&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);for(const m of messages)if(m.type===M.NEW_TURN)turn++;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));if(state===S.END)throw Error('Duel ended');if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){
     const indexFor=code=>p.activates.findIndex(c=>c.code===code);
     if(!prepared){const index=indexFor(setup);if(index<0)throw Error('Setup unavailable');prepared=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if((test.peas||test.marsh)&&test.normal&&!activated){const index=p.summons.findIndex(c=>c.code===source);if(index<0)throw Error('Peaskeeper Normal Summon unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_SUMMON,index});continue;}
     if(test.send){const gc=query(L.GRAVE).find(c=>c?.code===boss);if(!gc||(gc.reason&0x40)===0||(gc.reason&0x8000000)!==0)throw Error('Actual non-excavation send reasons mismatch');if(query(L.MZONE).some(c=>c?.code===ally)!==test.sylvan)throw Error('Sylvan versus unrelated effect-send trigger mismatch');done=true;continue;}
     if((test.sage||test.guard)&&!activated){const index=p.activates.findIndex(c=>c.code===source&&String(c.description)===String(source*16+(test.guard||test.hermit?0:1)));if(index<0)throw Error('Sagequoia ignition unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if(test.official||test.snuff||test.sage||test.cherub||test.peas||test.marsh||test.guard){if(test.plantTop){if(!query(test.macro?L.REMOVED:L.GRAVE).some(c=>c?.code===plant&&(c.reason&0x8000000)&&(c.reason&0x40)))throw Error('Sagequoia ordinary Plant excavation failed');}else if(test.nonplantTop){if(query(L.DECK).filter(Boolean)[0]?.code!==nonplant||query(L.GRAVE).some(c=>c?.code===nonplant))throw Error('Sagequoia ordinary non-Plant bottom movement failed');}else if(!query(L.GRAVE).some(c=>c?.code===boss&&(c.reason&0x8000000))||!query(L.MZONE).some(c=>c?.code===ally)||!trace.some(m=>m.type===M.CONFIRM_DECKTOP&&m.cards.some(c=>c.code===boss)))throw Error('Official Sylvan excavation/send/recruitment failed');if((test.sage||test.guard)&&p.activates.some(c=>c.code===source&&String(c.description)===String(source*16+(test.guard||test.hermit?0:1))))throw Error('Sagequoia soft count failed');if((test.cherub||test.marsh)&&!trace.some(m=>m.type===M.CONFIRM_DECKTOP&&m.cards.length===(test.two?2:1)&&m.cards[0].code===boss))throw Error('Cherubsprout chosen excavation count mismatch');if((test.cherub||test.marsh)&&test.two&&query(L.DECK).filter(Boolean)[0]?.code!==nonplant)throw Error('Cherubsprout remaining card bottom movement failed');if(test.guard&&!trace.some(m=>m.type===M.CONFIRM_DECKTOP&&m.cards.length===test.guard&&m.cards[0].code===boss))throw Error('Guardioak selected count mismatch');if(test.guard>1&&JSON.stringify(query(L.DECK).filter(Boolean).slice(0,test.guard-1).map(c=>c.code))!==JSON.stringify(test.guard===2?[nonplant]:bottom))throw Error('Guardioak actual bottom order mismatch');if(test.hermit){if(query(L.HAND).filter(c=>c?.code===filler).length!==(test.plantTop&&!test.macro?1:0))throw Error('Hermitree conditional draw mismatch');}done=true;continue;}
     if(!activated){const index=indexFor(boss);if(test.short){if(index>=0)throw Error('Short-Deck illegal activation offered');done=true;continue;}if(index<0)throw Error('Greetings unavailable');activated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if(!plantSummoned){const hand=query(L.HAND),gy=query(L.GRAVE),deck=query(L.DECK).filter(Boolean).map(c=>c.code);if(hand.filter(c=>c?.code===sa||c?.code===sb).length!==test.add)throw Error('Optional addition count mismatch');if(!gy.some(c=>c?.code===plant&&(c.reason&0x8000000)))throw Error('Plant not excavated');if(bottom.length&&JSON.stringify(deck.slice(0,bottom.length))!==JSON.stringify(bottom))throw Error('Actual bottom ordering mismatch');if(test.forced&&(!gy.some(c=>c?.code===boss&&(c.reason&0x8000000))||!query(L.MZONE).some(c=>c?.code===ally)))throw Error('Forced Greetings send/recruitment missing');if(indexFor(np)>=0)throw Error('Non-Plant Summon allowed under lock');const index=indexFor(pp);if(index<0)throw Error('Plant Summon blocked');plantSummoned=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}
     if(!query(L.MZONE).some(c=>c?.code===plant))throw Error('Actual Plant Summon failed');if(turn<3){if(turn===1&&indexFor(np)>=0)throw Error('Lock expired early');core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}
     if(!otherSummoned){const index=indexFor(np);if(index<0)throw Error('Plant lock did not expire');otherSummoned=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});continue;}if(!query(L.MZONE).some(c=>c?.code===nonplant))throw Error('Actual unlocked Summon failed');done=true;
    }else if(p.type===M.SELECT_CHAIN){const index=p.selects.findIndex(c=>(c.code===boss&&String(c.description)===String(132276575*16+2))||((test.official||test.snuff||test.cherub||test.peas||test.marsh)&&c.code===source));core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index>=0?index:p.forced?0:null});}
    else if(p.type===M.SELECT_EFFECTYN)core.duelSetResponse(duel,{type:R.SELECT_EFFECTYN,yes:true});
    else if(p.type===M.SELECT_YESNO)core.duelSetResponse(duel,{type:R.SELECT_YESNO,yes:test.add>0});
    else if(p.type===M.SELECT_CARD){const wanted=p.selects.some(c=>c.code===ally)?[ally]:[sa,sb];if(p.selects.some(c=>c.code===boss))throw Error('Forced-send Greetings offered as optional addition');const indices=p.selects.map((c,i)=>wanted.includes(c.code)?i:-1).filter(i=>i>=0).slice(0,wanted[0]===ally?1:test.add);core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:indices});}
    else if(p.type===M.SORT_CARD){const order=p.cards.map((_,i)=>i);bottom=p.cards.map(c=>c.code).reverse();const encoded={length:order[0],*[Symbol.iterator](){yield* order.slice(1);}};core.duelSetResponse(duel,{type:R.SORT_CARD,order:encoded});}
    else if(p.type===M.SELECT_PLACE){let location=L.MZONE,sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);if(sequence===undefined){location=L.SZONE;sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<(8+i)))===0);}core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location,sequence}]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else if(p.type===M.ANNOUNCE_NUMBER)core.duelSetResponse(duel,{type:R.ANNOUNCE_NUMBER,value:test.guard?test.guard-1:(test.cherub||test.marsh)&&test.two?1:0});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }if(!done)throw Error('Step limit');
  }catch(e){failure=e.message}finally{core.destroyDuel(duel)}
  results.push({...test,failure,trace,logs});console.log(`${failure?'FAIL':'PASS'} ${JSON.stringify(test)}${failure?': '+failure:''}`);
 }
 const control=['--no-lock','--original-official','--old-setcode','--any-effect-source','--require-reveal'].find(flag=>process.argv.includes(flag));
 fs.writeFileSync(path.join(ROOT,`output/fresh-ccg-september/sylvan-greetings${control?control.slice(1):''}.json`),JSON.stringify({engine:'Public OCGCore with complete Greetings/shared helper and production Komushroomo integration; neutral cards and real reorder/flip/Summon-probe Spells; actual next own turn verifies lock expiry; native Omega untested',adapter:'SORT_CARD response byte adapter documented in Flamushroomo audit; no Lua/core effect adapter',control:control||null,results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(r=>r.failure))process.exitCode=1;
}main().catch(e=>{console.error(e);process.exitCode=1});
