'use strict';
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{DatabaseSync}=require('node:sqlite');
const ROOT=path.resolve(__dirname,'..'),CUSTOM=path.join(ROOT,'public/CCG Downloads/CCG_Scripts'),OMEGA=path.join(ROOT,'tmp/omega_scripts');
async function main(){
 const mod=await import(pathToFileURL(path.join(path.dirname(require.resolve('@n1xx1/ocgcore-wasm')),'dist/index.js')).href);
 const {OcgMessageType:M,OcgResponseType:R,OcgLocation:L,OcgPosition:P,OcgProcessResult:S,SelectIdleCMDAction:A,OcgQueryFlags:Q}=mod;
 const core=await mod.default({sync:true,print(){},printErr(){}}),boss=238276249,victim=900000891,spell=900000892,enemy=900000893,filler=900000894,msg=132276249;
 const db=new DatabaseSync(path.join(ROOT,'output/fresh-ccg-september/candidate-CCG_v1.db'),{readOnly:true}),row=db.prepare('select * from datas where id=?').get(boss);db.close();
 const base={alias:0,setcodes:[],type:33,level:2,attribute:8,race:2n,attack:300,defense:200,lscale:0,rscale:0,link_marker:0},results=[];
 for(const test of (process.argv.includes('--reset')?[{member:true}]:[{member:true},{member:true,grave:true},{member:false},{member:true,decline:true},{member:true,full:true},{member:true,noVictim:true},{member:true,normal:true}])){
  const legal=test.normal||(!test.full&&!test.noVictim),canSearch=legal&&!test.normal&&test.member,logs=[],trace=[],cards=new Map([[boss,{...base,code:boss,setcodes:[0x11f],type:Number(row.type),level:Number(row.level)&255,attribute:Number(row.attribute),race:BigInt(row.race),attack:Number(row.atk),defense:Number(row.def)}],[victim,{...base,code:victim,setcodes:test.member?[0x11f]:[]}],[spell,{...base,code:spell,type:2,level:0,setcodes:[0x11f]}],[enemy,{...base,code:enemy}],[filler,{...base,code:filler}]]);
  const reader=name=>{if(name===`c${victim}.lua`)return `local s,id=GetID() function s.initial_effect(c) local e=Effect.CreateEffect(c) e:SetDescription(1) e:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O) e:SetProperty(EFFECT_FLAG_DELAY) e:SetCode(EVENT_TO_GRAVE) e:SetOperation(function(e,tp) Duel.Damage(tp,777,REASON_EFFECT) end) c:RegisterEffect(e) local g=Effect.CreateEffect(c) g:SetDescription(2) g:SetType(EFFECT_TYPE_IGNITION) g:SetRange(LOCATION_GRAVE) g:SetCountLimit(1) g:SetOperation(function(e,tp) Duel.Damage(tp,100,REASON_EFFECT) end) c:RegisterEffect(g) end`;if([spell,enemy,filler].some(c=>name===`c${c}.lua`))return 'local s,id=GetID() function s.initial_effect(c) end';if(name==='c0.lua')return '';const file=[path.join(CUSTOM,name),path.join(OMEGA,name)].find(f=>fs.existsSync(f));if(!file)throw Error('Missing '+name);let source=fs.readFileSync(file,'utf8');if(name===`c${boss}.lua`){if(process.argv.includes('--no-lock'))source=source.replace('Duel.RegisterEffect(lock,tp)','--negative control omits activation lock');if(process.argv.includes('--name-lock'))source=source.replace('re:GetHandler()==tc','re:GetHandler():IsCode(tc:GetCode())');}return source};
  const duel=core.createDuel({flags:mod.OcgDuelMode.MODE_MR5|mod.OcgDuelMode.PSEUDO_SHUFFLE,seed:[1n,2n,3n,4n],team1:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},team2:{startingLP:8000,startingDrawCount:0,drawCountPerTurn:0},cardReader:c=>cards.get(c),scriptReader:reader,errorHandler:(type,message)=>logs.push({type,message})});
  let failure=null,activated=false,searched=false,otherCopy=false,done=false,turn=0,resetting=false,resetActivated=false;
  try{
   for(const name of ['constant.lua','utility.lua','procedure.lua'])core.loadScript(duel,name,reader(name));
   const add=(code,location,player=0,sequence=0)=>core.duelNewCard(duel,{team:player,duelist:0,code,controller:player,location,sequence,position:P.FACEUP_ATTACK});add(boss,L.HAND);if(!test.noVictim)add(boss,L.HAND);if(!test.noVictim)add(victim,L.HAND);add(victim,L.GRAVE);add(spell,test.grave?L.GRAVE:L.DECK);add(enemy,L.MZONE,1);if(test.full)for(let i=0;i<5;i++)add(filler,L.MZONE,0,i);for(const player of [0,1])for(let i=0;i<5;i++)add(filler,L.DECK,player);
   core.startDuel(duel);
   for(let step=0;step<120&&!done;step++){
    const state=core.duelProcess(duel),messages=core.duelGetMessage(duel);trace.push(...messages);turn+=messages.filter(m=>m.type===M.NEW_TURN).length;if(logs.some(x=>x.type===0))throw Error(logs.map(x=>x.message).join('; '));if(state===S.END)throw Error('Duel ended');if(state!==S.WAITING)continue;const p=messages.at(-1);
    if(p.type===M.SELECT_IDLECMD){if(resetting){if(turn<3){core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}const available=p.activates.filter(c=>c.code===victim&&c.location===L.GRAVE);if(!resetActivated){if(available.length!==2)throw Error('Restriction/count did not expire');const card=available.find(c=>c.sequence===1);if(!card)throw Error('Previously destroyed physical copy unavailable');resetActivated=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index:p.activates.indexOf(card)});continue;}if(trace.filter(t=>t.type===M.DAMAGE&&t.amount===100).length!==2)throw Error('Previously destroyed card did not resolve after reset');done=true;continue;}const index=p.activates.findIndex(c=>c.code===boss&&String(c.description)===String(msg*16));if(legal&&!activated){activated=true;if(test.normal){const n=p.summons.findIndex(c=>c.code===boss);if(n<0)throw Error('Normal Summon missing');core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_SUMMON,index:n});}else{if(index<0)throw Error('Quick hand effect missing');core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index});}continue;}if(!test.normal&&index>=0)throw Error('Illegal/repeated Quick activation');if(legal){if(searched!==canSearch)throw Error('Conditional search prompt mismatch');const field=core.duelQueryLocation(duel,{flags:Q.CODE,controller:0,location:L.MZONE}),hand=core.duelQueryLocation(duel,{flags:Q.CODE,controller:0,location:L.HAND}),gy=core.duelQueryLocation(duel,{flags:Q.CODE,controller:1,location:L.GRAVE});if(!field.some(c=>c?.code===boss)||!gy.some(c=>c?.code===enemy))throw Error('Summon/opponent destruction failed');if(hand.some(c=>c?.code===spell)!==(canSearch&&!test.decline))throw Error('Spell search outcome mismatch');if(!test.normal){const effects=p.activates.filter(c=>c.code===victim&&c.location===L.GRAVE);if(effects.length!==(otherCopy?0:1)||(!otherCopy&&effects[0].sequence!==0))throw Error('Wrong physical card activation restriction');if(!otherCopy){otherCopy=true;const n=p.activates.indexOf(effects[0]);core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.SELECT_ACTIVATE,index:n});continue;}if(!trace.some(t=>t.type===M.DAMAGE&&t.amount===100)||trace.some(t=>t.type===M.DAMAGE&&t.amount===777))throw Error('Other copy damage/blocked trigger mismatch');}}if(process.argv.includes('--reset')){resetting=true;core.duelSetResponse(duel,{type:R.SELECT_IDLECMD,action:A.TO_EP});continue;}done=true;}
    else if(p.type===M.SELECT_YESNO){searched=true;core.duelSetResponse(duel,{type:R.SELECT_YESNO,yes:!test.decline});}
    else if(p.type===M.SELECT_EFFECTYN){if(p.code===victim)throw Error('Destroyed victim trigger offered');core.duelSetResponse(duel,{type:R.SELECT_EFFECTYN,yes:true});}
    else if(p.type===M.SELECT_CHAIN){if(p.selects.some(c=>c.code===victim))throw Error('Destroyed victim trigger offered');const index=p.selects.findIndex(c=>c.code===boss&&String(c.description)===String(msg*16+1));core.duelSetResponse(duel,{type:R.SELECT_CHAIN,index:index<0?null:index});}
    else if(p.type===M.SELECT_CARD){const wanted=p.selects.some(c=>c.code===spell)?spell:p.selects.some(c=>c.code===enemy)?enemy:victim,index=p.selects.findIndex(c=>c.code===wanted);if(index<0)throw Error('Effect candidate missing');core.duelSetResponse(duel,{type:R.SELECT_CARD,indicies:[index]});}
    else if(p.type===M.SELECT_PLACE){const sequence=[0,1,2,3,4].find(i=>(p.field_mask&(1<<i))===0);core.duelSetResponse(duel,{type:R.SELECT_PLACE,places:[{player:0,location:L.MZONE,sequence}]});}
    else if(p.type===M.SELECT_POSITION)core.duelSetResponse(duel,{type:R.SELECT_POSITION,position:P.FACEUP_ATTACK});
    else throw Error('Unhandled '+JSON.stringify(p,(_,v)=>typeof v==='bigint'?String(v):v));
   }
   if(!done)throw Error('Step limit');
  }catch(e){failure=e.message}finally{core.destroyDuel(duel)}
  results.push({...test,failure,searched,otherCopy,trace,logs});console.log(`${failure?'FAIL':'PASS'} ${JSON.stringify(test)}${failure?': '+failure:''}`);
 }
 fs.writeFileSync(path.join(ROOT,`output/fresh-ccg-september/nephthys-apostle-hand${process.argv.includes('--reset')?'-reset':process.argv.includes('--no-lock')?'-no-lock':process.argv.includes('--name-lock')?'-name-lock':''}.json`),JSON.stringify({engine:'public OCGCore with complete Apostle; not native Omega',qualifiers:['Victim fixture has real GY trigger and ignition; second same-code copy is initialized in GY','No restriction is mocked; activation offers, physical GY sequence, and actual damage are asserted'],results},(_,v)=>typeof v==='bigint'?String(v):v,2)+'\n');if(results.some(r=>r.failure))process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1});
