"""Audit and smoke-test every payload consumed by the Omega CCG installer."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sqlite3
import sys
import tempfile
import zipfile
from pathlib import Path

# This verifier imports the build modules for a read-only audit. Keep those
# imports from dirtying release folders with generated bytecode.
sys.dont_write_bytecode = True

from package_omega_ccg_scripts import collect_scripts, load_card_ids, verify_archive
from sync_omega_ccg_db import EXTRA_TOKEN_CARDS, build_message_carrier_map


REPO_ROOT = Path(__file__).resolve().parents[1]
CARDS_PATH = REPO_ROOT / "src" / "data" / "cards.json"
DOWNLOADS = REPO_ROOT / "public" / "CCG Downloads"
DB_PATH = DOWNLOADS / "CCG_Database" / "CCG_v1.db"
DB_ZIP_PATH = DOWNLOADS / "CCG_Database" / "CCG_Database.zip"
SCRIPTS_DIR = DOWNLOADS / "CCG_Scripts"
SCRIPTS_ZIP_PATH = SCRIPTS_DIR / "CCG_Scripts.zip"
BANLIST_PATH = DOWNLOADS / "CCG_Banlist" / "CCG_Banlist.lflist.conf"
INSTALLER_PATH = DOWNLOADS / "CCG_Omega_Addon_Setup.exe"
INSTALLER_SOURCE = REPO_ROOT / "scripts" / "ccg-omega-installer.iss"
INSTALLER_BUILD_PATH = REPO_ROOT / "scripts" / "output" / "CCG_Omega_Addon_Setup.exe"
DOWNLOADS_PAGE_SOURCE = REPO_ROOT / "src" / "pages" / "Downloads.tsx"


class Audit:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.notes: list[str] = []

    def require(self, condition: bool, message: str) -> None:
        if not condition:
            self.errors.append(message)

    def note(self, message: str) -> None:
        self.notes.append(message)


def archive_parts(directory: Path, base: str) -> list[Path]:
    pattern = re.compile(rf"^{re.escape(base)}(\d+)\.zip$")
    matches: list[tuple[int, Path]] = []
    for path in directory.glob(f"{base}*.zip"):
        match = pattern.fullmatch(path.name)
        if match:
            matches.append((int(match.group(1)), path))
    matches.sort()
    return [path for _part, path in matches]


def audit_image_group(
    audit: Audit,
    label: str,
    parts: list[Path],
    base: str,
    extension: str,
    expected_ids: set[int],
) -> None:
    expected_part_names = [f"{base}{index}.zip" for index in range(1, len(parts) + 1)]
    audit.require(
        [path.name for path in parts] == expected_part_names,
        f"{label}: archive part numbers are not contiguous from 1",
    )
    names: list[str] = []
    for path in parts:
        try:
            with zipfile.ZipFile(path, "r") as archive:
                bad_member = archive.testzip()
                audit.require(bad_member is None, f"{label}: corrupt member {bad_member} in {path.name}")
                names.extend(archive.namelist())
        except (OSError, zipfile.BadZipFile) as exc:
            audit.errors.append(f"{label}: cannot read {path.name}: {exc}")
    valid_name = re.compile(rf"^(\d+)\.{re.escape(extension)}$")
    invalid = sorted(name for name in names if valid_name.fullmatch(name) is None)
    actual_ids = {
        int(match.group(1))
        for name in names
        if (match := valid_name.fullmatch(name)) is not None
    }
    audit.require(not invalid, f"{label}: invalid/non-card entries: {invalid}")
    audit.require(len(names) == len(set(names)), f"{label}: duplicate archive entries")
    missing = sorted(expected_ids - actual_ids)
    extra = sorted(actual_ids - expected_ids)
    audit.require(not missing, f"{label}: missing IDs {missing}")
    audit.require(not extra, f"{label}: non-CCG IDs {extra}")
    audit.note(f"{label}: {len(actual_ids)} cards across {len(parts)} archive part(s)")


def audit_database(audit: Audit, cards: list[dict], active_ids: set[int]) -> set[int]:
    token_ids = {int(token["id"]) for token in EXTRA_TOKEN_CARDS}
    carrier_ids = set(build_message_carrier_map(cards).values())
    expected_ids = active_ids | token_ids | carrier_ids
    try:
        connection = sqlite3.connect(DB_PATH)
        data_ids = {int(row[0]) for row in connection.execute("select id from datas")}
        text_ids = {int(row[0]) for row in connection.execute("select id from texts")}
        integrity = connection.execute("pragma integrity_check").fetchone()[0]
        connection.close()
    except (OSError, sqlite3.DatabaseError) as exc:
        audit.errors.append(f"database: cannot read CCG_v1.db: {exc}")
        return expected_ids

    audit.require(integrity == "ok", f"database: integrity_check returned {integrity!r}")
    audit.require(data_ids == text_ids, "database: datas/texts ID membership differs")
    audit.require(data_ids == expected_ids, f"database: unexpected IDs {sorted(data_ids - expected_ids)}")
    audit.require(active_ids <= data_ids, f"database: missing active cards {sorted(active_ids - data_ids)}")

    try:
        with zipfile.ZipFile(DB_ZIP_PATH, "r") as archive:
            audit.require(archive.namelist() == ["CCG_v1.db"], "database ZIP: expected one root CCG_v1.db")
            audit.require(archive.read("CCG_v1.db") == DB_PATH.read_bytes(), "database ZIP: DB content is stale")
    except (OSError, KeyError, zipfile.BadZipFile) as exc:
        audit.errors.append(f"database ZIP: cannot read payload: {exc}")

    audit.note(
        f"database: {len(active_ids)} cards, {len(token_ids)} CCG Tokens, "
        f"{len(carrier_ids)} hidden prompt carriers"
    )
    return expected_ids


def audit_installer_constants(audit: Audit, groups: dict[str, list[Path]]) -> None:
    try:
        source = INSTALLER_SOURCE.read_text(encoding="utf-8")
    except OSError as exc:
        audit.errors.append(f"installer: cannot read source: {exc}")
        return
    constant_groups = {
        "IMAGE_PART_COUNT": groups["Arts"],
        "PICS_PART_COUNT": groups["Pics"],
        "HOLOGRAM_PART_COUNT": groups["Holograms"],
    }
    for constant, parts in constant_groups.items():
        match = re.search(rf"\b{constant}\s*=\s*(\d+)\s*;", source)
        audit.require(match is not None, f"installer: missing {constant}")
        if match:
            audit.require(
                int(match.group(1)) == len(parts),
                f"installer: {constant}={match.group(1)} but found {len(parts)} part(s)",
            )
    audit.require(INSTALLER_PATH.is_file(), "installer: published EXE is missing")
    if INSTALLER_PATH.is_file():
        audit.require(INSTALLER_BUILD_PATH.is_file(), "installer: compiler output EXE is missing")
        if INSTALLER_BUILD_PATH.is_file():
            audit.require(
                INSTALLER_PATH.read_bytes() == INSTALLER_BUILD_PATH.read_bytes(),
                "installer: published EXE differs from the compiler output",
            )
        audit.note(f"installer: compiled EXE present ({INSTALLER_PATH.stat().st_size:,} bytes)")


def audit_website_downloads(audit: Audit, groups: dict[str, list[Path]]) -> None:
    try:
        source = DOWNLOADS_PAGE_SOURCE.read_text(encoding="utf-8")
    except OSError as exc:
        audit.errors.append(f"website downloads: cannot read source: {exc}")
        return

    advertised = {
        "Arts": {
            int(value)
            for value in re.findall(r"YGO_Omega_Images_v(\d+)\.zip", source)
        },
        "Pics": {
            int(value)
            for value in re.findall(r"YGO_Omega_Pics_v(\d+)\.zip", source)
        },
        "Holograms": {
            int(value)
            for value in re.findall(r"YGO_Omega_Holograms_v(\d+)\.zip", source)
        },
    }
    for label, parts in groups.items():
        expected = set(range(1, len(parts) + 1))
        audit.require(
            advertised[label] == expected,
            f"website downloads: {label} links {sorted(advertised[label])}, "
            f"expected {sorted(expected)}",
        )
    audit.require(
        "CCG%20Downloads/CCG_Omega_Addon_Setup.exe" in source,
        "website downloads: installer button does not target the published EXE",
    )
    audit.require(
        'download="CCG_Omega_Addon_Setup.exe"' in source,
        "website downloads: installer link does not explicitly request a download",
    )
    audit.note("website downloads: installer and manual part links match the release")


def smoke_extract(
    audit: Audit,
    active_ids: set[int],
    monster_ids: set[int],
    expected_db_ids: set[int],
    groups: dict[str, list[Path]],
) -> None:
    with tempfile.TemporaryDirectory(prefix="ccg-omega-installer-") as temp_name:
        files_root = Path(temp_name) / "YGO Omega_Data" / "Files"
        destinations = {
            "Arts": files_root / "Arts",
            "Pics": files_root / "Pics",
            "Holograms": files_root / "Holograms",
        }
        database_dir = files_root / "Databases"
        scripts_dir = files_root / "Scripts"
        banlist_dir = files_root / "Banlists"
        for directory in [*destinations.values(), database_dir, scripts_dir, banlist_dir]:
            directory.mkdir(parents=True, exist_ok=True)

        # Model an existing Omega installation. Files with matching payload
        # names must be replaced, while unrelated and formerly shipped names
        # must survive byte-for-byte.
        active_id = min(active_ids)
        monster_id = min(monster_ids)
        retired_id = 210711859
        old_content = b"pre-existing content that must be replaced"
        keep_content = b"unrelated content that must not be touched"
        replacement_targets = [
            scripts_dir / f"c{active_id}.lua",
            destinations["Arts"] / f"{active_id}.jpg",
            destinations["Pics"] / f"{active_id}.jpg",
            destinations["Holograms"] / f"{monster_id}.png",
            database_dir / "CCG_v1.db",
            banlist_dir / BANLIST_PATH.name,
        ]
        preserved_targets = [
            scripts_dir / f"c{retired_id}.lua",
            destinations["Arts"] / f"{retired_id}.jpg",
            destinations["Pics"] / f"{retired_id}.jpg",
            destinations["Holograms"] / f"{retired_id}.png",
        ]
        for directory in [*destinations.values(), database_dir, scripts_dir, banlist_dir]:
            preserved_targets.append(directory / "unrelated.keep")
        for path in replacement_targets:
            path.write_bytes(old_content)
        for path in preserved_targets:
            path.write_bytes(keep_content)

        for label, parts in groups.items():
            for part in parts:
                with zipfile.ZipFile(part, "r") as archive:
                    archive.extractall(destinations[label])

        with zipfile.ZipFile(DB_ZIP_PATH, "r") as archive:
            archive.extractall(database_dir)
        with zipfile.ZipFile(SCRIPTS_ZIP_PATH, "r") as archive:
            archive.extractall(scripts_dir)
        shutil.copy2(BANLIST_PATH, banlist_dir / BANLIST_PATH.name)

        def read_member(parts: list[Path], member_name: str) -> bytes:
            for part in parts:
                with zipfile.ZipFile(part, "r") as archive:
                    if member_name in archive.namelist():
                        return archive.read(member_name)
            raise KeyError(member_name)

        with zipfile.ZipFile(SCRIPTS_ZIP_PATH, "r") as archive:
            expected_script = archive.read(f"c{active_id}.lua")
        expected_replacements = {
            scripts_dir / f"c{active_id}.lua": expected_script,
            destinations["Arts"] / f"{active_id}.jpg": read_member(
                groups["Arts"], f"{active_id}.jpg"
            ),
            destinations["Pics"] / f"{active_id}.jpg": read_member(
                groups["Pics"], f"{active_id}.jpg"
            ),
            destinations["Holograms"] / f"{monster_id}.png": read_member(
                groups["Holograms"], f"{monster_id}.png"
            ),
            database_dir / "CCG_v1.db": DB_PATH.read_bytes(),
            banlist_dir / BANLIST_PATH.name: BANLIST_PATH.read_bytes(),
        }

        installed_scripts = {
            int(match.group(1))
            for path in scripts_dir.iterdir()
            if (match := re.fullmatch(r"c(\d+)\.lua", path.name)) is not None
        }
        installed_arts = {
            int(match.group(1))
            for path in destinations["Arts"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.jpg", path.name)) is not None
        }
        installed_pics = {
            int(match.group(1))
            for path in destinations["Pics"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.jpg", path.name)) is not None
        }
        installed_holograms = {
            int(match.group(1))
            for path in destinations["Holograms"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.png", path.name)) is not None
        }
        audit.require(
            installed_scripts == active_ids | {retired_id},
            "smoke install: Scripts membership differs",
        )
        audit.require(
            installed_arts == active_ids | {retired_id},
            "smoke install: Arts membership differs",
        )
        audit.require(
            installed_pics == active_ids | {retired_id},
            "smoke install: Pics membership differs",
        )
        audit.require(
            installed_holograms == monster_ids | {retired_id},
            "smoke install: Holograms membership differs",
        )
        for path, expected_content in expected_replacements.items():
            audit.require(
                path.read_bytes() == expected_content,
                f"smoke install: matching file was not replaced exactly: {path.name}",
            )
        for path in preserved_targets:
            audit.require(
                path.read_bytes() == keep_content,
                f"smoke install: unrelated file was changed/deleted: {path.name}",
            )

        connection = sqlite3.connect(database_dir / "CCG_v1.db")
        installed_db_ids = {int(row[0]) for row in connection.execute("select id from datas")}
        connection.close()
        audit.require(installed_db_ids == expected_db_ids, "smoke install: database membership differs")
        audit.note(
            "smoke install: correct folders; matching files replaced; "
            "new files added; unrelated files preserved"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit the complete Omega CCG installer release.")
    parser.add_argument("--no-smoke", action="store_true", help="Skip isolated payload extraction.")
    args = parser.parse_args()
    audit = Audit()

    try:
        cards = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
        active_ids = load_card_ids(CARDS_PATH)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cards source failed: {exc}") from exc
    monster_ids = {
        int(card["passcode"])
        for card in cards
        if str(card.get("category")) == "Monster"
    }
    audit.note(f"source: {len(active_ids)} unique active CCG card IDs")

    try:
        script_paths = collect_scripts(SCRIPTS_DIR, active_ids)
        verify_archive(script_paths, SCRIPTS_ZIP_PATH)
        audit.note(f"scripts: {len(script_paths)} standalone card scripts; no helpers/orphans")
    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        audit.errors.append(f"scripts: {exc}")

    expected_db_ids = audit_database(audit, cards, active_ids)
    groups = {
        "Arts": archive_parts(DOWNLOADS, "YGO_Omega_Images_v"),
        "Pics": archive_parts(DOWNLOADS / "YGO_Omega_Images", "YGO_Omega_Pics_v"),
        "Holograms": archive_parts(DOWNLOADS / "YGO_Omega_Images", "YGO_Omega_Holograms_v"),
    }
    audit_image_group(audit, "Arts", groups["Arts"], "YGO_Omega_Images_v", "jpg", active_ids)
    audit_image_group(audit, "Pics", groups["Pics"], "YGO_Omega_Pics_v", "jpg", active_ids)
    audit_image_group(
        audit,
        "Holograms",
        groups["Holograms"],
        "YGO_Omega_Holograms_v",
        "png",
        monster_ids,
    )
    audit.require(BANLIST_PATH.is_file() and BANLIST_PATH.stat().st_size > 0, "banlist: payload is missing/empty")
    audit_installer_constants(audit, groups)
    audit_website_downloads(audit, groups)

    if not args.no_smoke and not audit.errors:
        smoke_extract(audit, active_ids, monster_ids, expected_db_ids, groups)

    for note in audit.notes:
        print(f"PASS  {note}")
    if audit.errors:
        for error in audit.errors:
            print(f"FAIL  {error}")
        print(f"\nOmega release audit failed with {len(audit.errors)} error(s).")
        return 1
    print("\nOmega release audit passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
