"""Audit and smoke-test every payload consumed by the Omega CCG installer."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sqlite3
import sys
import tempfile
import zipfile
from contextlib import ExitStack
from io import BytesIO
from pathlib import Path

from PIL import Image, UnidentifiedImageError

# This verifier imports the build modules for a read-only audit. Keep those
# imports from dirtying release folders with generated bytecode.
sys.dont_write_bytecode = True

from package_omega_ccg_scripts import (
    COMPATIBILITY_SCRIPT_IDS,
    collect_scripts,
    load_card_ids,
    verify_archive,
)
from sync_omega_ccg_db import (
    EXTRA_TOKEN_CARDS,
    build_data_row,
    build_existing_setcode_map,
    build_message_carrier_map,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
CARDS_PATH = REPO_ROOT / "src" / "data" / "cards.json"
DOWNLOADS = REPO_ROOT / "public" / "CCG Downloads"
DB_PATH = DOWNLOADS / "CCG_Database" / "CCG_v1.db"
DB_ZIP_PATH = DOWNLOADS / "CCG_Database" / "CCG_Database.zip"
SCRIPTS_DIR = DOWNLOADS / "CCG_Scripts"
SCRIPTS_ZIP_PATH = SCRIPTS_DIR / "CCG_Scripts.zip"
BANLIST_PATH = DOWNLOADS / "CCG_Banlist" / "CCG_Banlist.lflist.conf"
INSTALLER_PATH = DOWNLOADS / "CCG_Omega_Addon_Setup.exe"
INSTALLER_SOURCE = REPO_ROOT / "scripts" / "ccg-omega-installer.iss"
INSTALLER_BUILD_PATH = REPO_ROOT / "scripts" / "output" / "CCG_Omega_Addon_Setup.exe"
DOWNLOADS_PAGE_SOURCE = REPO_ROOT / "src" / "pages" / "Downloads.tsx"
HOLOGRAM_SIZE = (512, 512)
MONSTER_ATTRIBUTES = {
    "DARK",
    "DIVINE",
    "EARTH",
    "ELECTRIC",
    "FIRE",
    "ICE",
    "LIGHT",
    "METAL",
    "NATURE",
    "WATER",
    "WIND",
}
SPELL_TRAP_ICONS = {
    None,
    "Normal",
    "Continuous",
    "Counter",
    "Equip",
    "Field",
    "Quick-Play",
    "Ritual",
}


class Audit:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.notes: list[str] = []

    def require(self, condition: bool, message: str) -> None:
        if not condition:
            self.errors.append(message)

    def note(self, message: str) -> None:
        self.notes.append(message)


def archive_parts(directory: Path, base: str) -> list[Path]:
    pattern = re.compile(rf"^{re.escape(base)}(\d+)\.zip$")
    matches: list[tuple[int, Path]] = []
    for path in directory.glob(f"{base}*.zip"):
        match = pattern.fullmatch(path.name)
        if match:
            matches.append((int(match.group(1)), path))
    matches.sort()
    return [path for _part, path in matches]


def audit_source_metadata(audit: Audit, cards: list[dict]) -> None:
    """Reject incomplete source rows before they can produce a partial Omega DB."""

    failures: list[str] = []
    for card in cards:
        card_id = card.get("passcode")
        name = str(card.get("name") or f"card {card_id}")
        category = card.get("category")
        prefix = f"{card_id} ({name})"
        if category not in {"Monster", "Spell", "Trap"}:
            failures.append(f"{prefix}: invalid category {category!r}")
            continue

        if category != "Monster":
            icon = card.get("icon")
            if icon not in SPELL_TRAP_ICONS:
                failures.append(f"{prefix}: invalid {category} icon {icon!r}")
            monster_only_fields = (
                "cardTypes",
                "monsterType",
                "attribute",
                "level",
                "rank",
                "linkRating",
                "linkArrows",
                "scale",
                "atk",
                "def",
            )
            populated_fields = [
                field
                for field in monster_only_fields
                if card.get(field) is not None
            ]
            if populated_fields:
                failures.append(
                    f"{prefix}: {category} has monster-only fields "
                    f"{', '.join(populated_fields)}"
                )
            continue

        card_types = card.get("cardTypes")
        monster_types = card.get("monsterType")
        attribute = card.get("attribute")
        if not isinstance(card_types, list) or not card_types:
            failures.append(f"{prefix}: missing cardTypes")
            continue
        if not isinstance(monster_types, list) or not monster_types:
            failures.append(f"{prefix}: missing monsterType")
        if attribute not in MONSTER_ATTRIBUTES:
            failures.append(f"{prefix}: invalid/missing attribute {attribute!r}")
        if not ({"Normal", "Effect"} & set(card_types)):
            failures.append(f"{prefix}: neither Normal nor Effect")
        if {"Normal", "Effect"} <= set(card_types):
            failures.append(f"{prefix}: both Normal and Effect")
        text = str(card.get("text") or "")
        if (
            re.search(r"Cannot be Normal Summoned/Set", text, re.IGNORECASE)
            and "Special Summon" not in card_types
        ):
            failures.append(f"{prefix}: missing Special Summon type")
        if (
            "Fusion" in card_types
            and re.search(
                r"Must (?:first )?be Special Summoned",
                text,
                re.IGNORECASE,
            )
            and "Special Summon" not in card_types
        ):
            failures.append(f"{prefix}: contact Fusion missing Special Summon type")

        if "Link" in card_types:
            rating = card.get("linkRating")
            arrows = card.get("linkArrows")
            if not isinstance(rating, int) or rating <= 0:
                failures.append(f"{prefix}: invalid/missing linkRating {rating!r}")
            if not isinstance(arrows, list) or len(arrows) != rating:
                failures.append(
                    f"{prefix}: linkArrows count does not match linkRating"
                )
        elif "Xyz" in card_types:
            rank = card.get("rank")
            if not isinstance(rank, int) or rank <= 0:
                failures.append(f"{prefix}: invalid/missing rank {rank!r}")
        else:
            level = card.get("level")
            if not isinstance(level, int) or level <= 0:
                failures.append(f"{prefix}: invalid/missing level {level!r}")

        if "Pendulum" in card_types and not isinstance(card.get("scale"), int):
            failures.append(f"{prefix}: missing Pendulum scale")

    audit.require(
        not failures,
        "source metadata: " + "; ".join(failures[:20]),
    )
    if not failures:
        audit.note(f"source metadata: {len(cards)} complete card rows")


def audit_image_group(
    audit: Audit,
    label: str,
    parts: list[Path],
    base: str,
    extension: str,
    expected_ids: set[int],
) -> None:
    expected_part_names = [f"{base}{index}.zip" for index in range(1, len(parts) + 1)]
    audit.require(
        [path.name for path in parts] == expected_part_names,
        f"{label}: archive part numbers are not contiguous from 1",
    )
    names: list[str] = []
    for path in parts:
        try:
            with zipfile.ZipFile(path, "r") as archive:
                bad_member = archive.testzip()
                audit.require(bad_member is None, f"{label}: corrupt member {bad_member} in {path.name}")
                names.extend(archive.namelist())
        except (OSError, zipfile.BadZipFile) as exc:
            audit.errors.append(f"{label}: cannot read {path.name}: {exc}")
    valid_name = re.compile(rf"^(\d+)\.{re.escape(extension)}$")
    invalid = sorted(name for name in names if valid_name.fullmatch(name) is None)
    actual_ids = {
        int(match.group(1))
        for name in names
        if (match := valid_name.fullmatch(name)) is not None
    }
    audit.require(not invalid, f"{label}: invalid/non-card entries: {invalid}")
    audit.require(len(names) == len(set(names)), f"{label}: duplicate archive entries")
    missing = sorted(expected_ids - actual_ids)
    extra = sorted(actual_ids - expected_ids)
    audit.require(not missing, f"{label}: missing IDs {missing}")
    audit.require(not extra, f"{label}: non-CCG IDs {extra}")
    audit.note(f"{label}: {len(actual_ids)} cards across {len(parts)} archive part(s)")


def audit_holograms_from_arts(
    audit: Audit,
    art_parts: list[Path],
    hologram_parts: list[Path],
    monster_ids: set[int],
) -> None:
    def summarize(ids: list[int]) -> str:
        preview = ", ".join(str(card_id) for card_id in ids[:10])
        if len(ids) > 10:
            preview += f", ... ({len(ids)} total)"
        return preview

    missing_art: list[int] = []
    missing_hologram: list[int] = []
    invalid_images: list[int] = []
    wrong_mode: list[int] = []
    wrong_size: list[int] = []
    transparent: list[int] = []
    mismatched_pixels: list[int] = []

    try:
        with ExitStack() as stack:
            art_archives = [
                stack.enter_context(zipfile.ZipFile(path, "r"))
                for path in art_parts
            ]
            hologram_archives = [
                stack.enter_context(zipfile.ZipFile(path, "r"))
                for path in hologram_parts
            ]
            art_sources = {
                name: archive
                for archive in art_archives
                for name in archive.namelist()
            }
            hologram_sources = {
                name: archive
                for archive in hologram_archives
                for name in archive.namelist()
            }

            for card_id in sorted(monster_ids):
                art_name = f"{card_id}.jpg"
                hologram_name = f"{card_id}.png"
                art_archive = art_sources.get(art_name)
                hologram_archive = hologram_sources.get(hologram_name)
                if art_archive is None:
                    missing_art.append(card_id)
                if hologram_archive is None:
                    missing_hologram.append(card_id)
                if art_archive is None or hologram_archive is None:
                    continue

                try:
                    with Image.open(BytesIO(art_archive.read(art_name))) as art_image:
                        expected = art_image.convert("RGB").resize(
                            HOLOGRAM_SIZE,
                            Image.Resampling.LANCZOS,
                        )
                    with Image.open(
                        BytesIO(hologram_archive.read(hologram_name))
                    ) as hologram_image:
                        hologram_image.load()
                        if hologram_image.mode != "RGBA":
                            wrong_mode.append(card_id)
                        if hologram_image.size != HOLOGRAM_SIZE:
                            wrong_size.append(card_id)
                            continue
                        hologram = hologram_image.convert("RGBA")
                except (
                    KeyError,
                    OSError,
                    UnidentifiedImageError,
                    zipfile.BadZipFile,
                ):
                    invalid_images.append(card_id)
                    continue

                if hologram.getchannel("A").getextrema() != (255, 255):
                    transparent.append(card_id)
                if hologram.convert("RGB").tobytes() != expected.tobytes():
                    mismatched_pixels.append(card_id)
    except (OSError, zipfile.BadZipFile) as exc:
        audit.errors.append(f"Holograms: cannot compare against primary Arts: {exc}")
        return

    for ids, message in [
        (missing_art, "monster IDs have no primary Art"),
        (missing_hologram, "monster IDs have no Hologram"),
        (invalid_images, "images could not be decoded"),
        (wrong_mode, "Holograms are not RGBA"),
        (wrong_size, "Holograms are not 512x512"),
        (transparent, "Holograms are not fully opaque"),
        (mismatched_pixels, "Holograms do not match resized primary Arts"),
    ]:
        audit.require(not ids, f"Holograms: {message}: {summarize(ids)}")

    if not any(
        [
            missing_art,
            missing_hologram,
            invalid_images,
            wrong_mode,
            wrong_size,
            transparent,
            mismatched_pixels,
        ]
    ):
        audit.note(
            f"Holograms: {len(monster_ids)} opaque primary Arts images at "
            f"{HOLOGRAM_SIZE[0]}x{HOLOGRAM_SIZE[1]}"
        )


def audit_database(audit: Audit, cards: list[dict], active_ids: set[int]) -> set[int]:
    token_ids = {int(token["id"]) for token in EXTRA_TOKEN_CARDS}
    carrier_ids = set(build_message_carrier_map(cards).values())
    expected_ids = active_ids | token_ids | carrier_ids
    row_mismatches: list[str] = []
    try:
        connection = sqlite3.connect(DB_PATH)
        connection.row_factory = sqlite3.Row
        data_ids = {int(row[0]) for row in connection.execute("select id from datas")}
        text_ids = {int(row[0]) for row in connection.execute("select id from texts")}
        integrity = connection.execute("pragma integrity_check").fetchone()[0]
        active_rows = [
            connection.execute(
                """
                select d.*, t.name
                from datas d left join texts t on d.id=t.id
                where d.id=?
                """,
                (int(card["passcode"]),),
            ).fetchone()
            for card in cards
        ]
        if all(row is not None for row in active_rows):
            setcode_map, used_setcodes = build_existing_setcode_map(
                cards,
                active_rows,
            )
            for card, row in zip(cards, active_rows):
                card_id = int(card["passcode"])
                expected = build_data_row(
                    card_id,
                    card,
                    setcode_map,
                    used_setcodes,
                    row,
                )
                changed = [
                    column
                    for column in (
                        "setcode",
                        "type",
                        "atk",
                        "def",
                        "level",
                        "race",
                        "attribute",
                    )
                    if row[column] != expected[column]
                ]
                if changed:
                    row_mismatches.append(
                        f"{card_id} ({card.get('name')}): "
                        f"{', '.join(changed)}"
                    )
        connection.close()
    except (OSError, sqlite3.DatabaseError) as exc:
        audit.errors.append(f"database: cannot read CCG_v1.db: {exc}")
        return expected_ids

    audit.require(integrity == "ok", f"database: integrity_check returned {integrity!r}")
    audit.require(data_ids == text_ids, "database: datas/texts ID membership differs")
    audit.require(data_ids == expected_ids, f"database: unexpected IDs {sorted(data_ids - expected_ids)}")
    audit.require(active_ids <= data_ids, f"database: missing active cards {sorted(active_ids - data_ids)}")
    audit.require(
        not row_mismatches,
        "database: source metadata differs for "
        + "; ".join(row_mismatches[:20]),
    )

    try:
        with zipfile.ZipFile(DB_ZIP_PATH, "r") as archive:
            audit.require(archive.namelist() == ["CCG_v1.db"], "database ZIP: expected one root CCG_v1.db")
            audit.require(archive.read("CCG_v1.db") == DB_PATH.read_bytes(), "database ZIP: DB content is stale")
    except (OSError, KeyError, zipfile.BadZipFile) as exc:
        audit.errors.append(f"database ZIP: cannot read payload: {exc}")

    audit.note(
        f"database: {len(active_ids)} cards, {len(token_ids)} CCG Tokens, "
        f"{len(carrier_ids)} hidden prompt carriers"
    )
    return expected_ids


def audit_installer_constants(audit: Audit, groups: dict[str, list[Path]]) -> None:
    try:
        source = INSTALLER_SOURCE.read_text(encoding="utf-8")
    except OSError as exc:
        audit.errors.append(f"installer: cannot read source: {exc}")
        return
    constant_groups = {
        "IMAGE_PART_COUNT": groups["Arts"],
        "PICS_PART_COUNT": groups["Pics"],
        "HOLOGRAM_PART_COUNT": groups["Holograms"],
    }
    for constant, parts in constant_groups.items():
        match = re.search(rf"\b{constant}\s*=\s*(\d+)\s*;", source)
        audit.require(match is not None, f"installer: missing {constant}")
        if match:
            audit.require(
                int(match.group(1)) == len(parts),
                f"installer: {constant}={match.group(1)} but found {len(parts)} part(s)",
            )
    audit.require(INSTALLER_PATH.is_file(), "installer: published EXE is missing")
    if INSTALLER_PATH.is_file():
        audit.require(INSTALLER_BUILD_PATH.is_file(), "installer: compiler output EXE is missing")
        if INSTALLER_BUILD_PATH.is_file():
            audit.require(
                INSTALLER_PATH.read_bytes() == INSTALLER_BUILD_PATH.read_bytes(),
                "installer: published EXE differs from the compiler output",
            )
        audit.note(f"installer: compiled EXE present ({INSTALLER_PATH.stat().st_size:,} bytes)")


def audit_website_downloads(audit: Audit, groups: dict[str, list[Path]]) -> None:
    try:
        source = DOWNLOADS_PAGE_SOURCE.read_text(encoding="utf-8")
    except OSError as exc:
        audit.errors.append(f"website downloads: cannot read source: {exc}")
        return

    advertised = {
        "Arts": {
            int(value)
            for value in re.findall(r"YGO_Omega_Images_v(\d+)\.zip", source)
        },
        "Pics": {
            int(value)
            for value in re.findall(r"YGO_Omega_Pics_v(\d+)\.zip", source)
        },
        "Holograms": {
            int(value)
            for value in re.findall(r"YGO_Omega_Holograms_v(\d+)\.zip", source)
        },
    }
    for label, parts in groups.items():
        expected = set(range(1, len(parts) + 1))
        audit.require(
            advertised[label] == expected,
            f"website downloads: {label} links {sorted(advertised[label])}, "
            f"expected {sorted(expected)}",
        )
    audit.require(
        "CCG%20Downloads/CCG_Omega_Addon_Setup.exe" in source,
        "website downloads: installer button does not target the published EXE",
    )
    audit.require(
        'download="CCG_Omega_Addon_Setup.exe"' in source,
        "website downloads: installer link does not explicitly request a download",
    )
    audit.note("website downloads: installer and manual part links match the release")


def smoke_extract(
    audit: Audit,
    active_ids: set[int],
    monster_ids: set[int],
    expected_db_ids: set[int],
    groups: dict[str, list[Path]],
) -> None:
    with tempfile.TemporaryDirectory(prefix="ccg-omega-installer-") as temp_name:
        files_root = Path(temp_name) / "YGO Omega_Data" / "Files"
        destinations = {
            "Arts": files_root / "Arts",
            "Pics": files_root / "Pics",
            "Holograms": files_root / "Holograms",
        }
        database_dir = files_root / "Databases"
        scripts_dir = files_root / "Scripts"
        banlist_dir = files_root / "Banlists"
        for directory in [*destinations.values(), database_dir, scripts_dir, banlist_dir]:
            directory.mkdir(parents=True, exist_ok=True)

        # Model an existing Omega installation. Files with matching payload
        # names must be replaced, while unrelated and formerly shipped names
        # must survive byte-for-byte.
        active_id = min(active_ids)
        monster_id = min(monster_ids)
        retired_id = 210711859
        old_content = b"pre-existing content that must be replaced"
        keep_content = b"unrelated content that must not be touched"
        replacement_targets = [
            scripts_dir / f"c{active_id}.lua",
            destinations["Arts"] / f"{active_id}.jpg",
            destinations["Pics"] / f"{active_id}.jpg",
            destinations["Holograms"] / f"{monster_id}.png",
            database_dir / "CCG_v1.db",
            banlist_dir / BANLIST_PATH.name,
        ]
        preserved_targets = [
            scripts_dir / f"c{retired_id}.lua",
            destinations["Arts"] / f"{retired_id}.jpg",
            destinations["Pics"] / f"{retired_id}.jpg",
            destinations["Holograms"] / f"{retired_id}.png",
        ]
        for directory in [*destinations.values(), database_dir, scripts_dir, banlist_dir]:
            preserved_targets.append(directory / "unrelated.keep")
        for path in replacement_targets:
            path.write_bytes(old_content)
        for path in preserved_targets:
            path.write_bytes(keep_content)

        for label, parts in groups.items():
            for part in parts:
                with zipfile.ZipFile(part, "r") as archive:
                    archive.extractall(destinations[label])

        with zipfile.ZipFile(DB_ZIP_PATH, "r") as archive:
            archive.extractall(database_dir)
        with zipfile.ZipFile(SCRIPTS_ZIP_PATH, "r") as archive:
            archive.extractall(scripts_dir)
        shutil.copy2(BANLIST_PATH, banlist_dir / BANLIST_PATH.name)

        def read_member(parts: list[Path], member_name: str) -> bytes:
            for part in parts:
                with zipfile.ZipFile(part, "r") as archive:
                    if member_name in archive.namelist():
                        return archive.read(member_name)
            raise KeyError(member_name)

        with zipfile.ZipFile(SCRIPTS_ZIP_PATH, "r") as archive:
            expected_script = archive.read(f"c{active_id}.lua")
        expected_replacements = {
            scripts_dir / f"c{active_id}.lua": expected_script,
            destinations["Arts"] / f"{active_id}.jpg": read_member(
                groups["Arts"], f"{active_id}.jpg"
            ),
            destinations["Pics"] / f"{active_id}.jpg": read_member(
                groups["Pics"], f"{active_id}.jpg"
            ),
            destinations["Holograms"] / f"{monster_id}.png": read_member(
                groups["Holograms"], f"{monster_id}.png"
            ),
            database_dir / "CCG_v1.db": DB_PATH.read_bytes(),
            banlist_dir / BANLIST_PATH.name: BANLIST_PATH.read_bytes(),
        }

        installed_scripts = {
            int(match.group(1))
            for path in scripts_dir.iterdir()
            if (match := re.fullmatch(r"c(\d+)\.lua", path.name)) is not None
        }
        installed_arts = {
            int(match.group(1))
            for path in destinations["Arts"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.jpg", path.name)) is not None
        }
        installed_pics = {
            int(match.group(1))
            for path in destinations["Pics"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.jpg", path.name)) is not None
        }
        installed_holograms = {
            int(match.group(1))
            for path in destinations["Holograms"].iterdir()
            if (match := re.fullmatch(r"(\d+)\.png", path.name)) is not None
        }
        audit.require(
            installed_scripts == active_ids | COMPATIBILITY_SCRIPT_IDS | {retired_id},
            "smoke install: Scripts membership differs",
        )
        audit.require(
            installed_arts == active_ids | {retired_id},
            "smoke install: Arts membership differs",
        )
        audit.require(
            installed_pics == active_ids | {retired_id},
            "smoke install: Pics membership differs",
        )
        audit.require(
            installed_holograms == monster_ids | {retired_id},
            "smoke install: Holograms membership differs",
        )
        for path, expected_content in expected_replacements.items():
            audit.require(
                path.read_bytes() == expected_content,
                f"smoke install: matching file was not replaced exactly: {path.name}",
            )
        for path in preserved_targets:
            audit.require(
                path.read_bytes() == keep_content,
                f"smoke install: unrelated file was changed/deleted: {path.name}",
            )

        connection = sqlite3.connect(database_dir / "CCG_v1.db")
        installed_db_ids = {int(row[0]) for row in connection.execute("select id from datas")}
        connection.close()
        audit.require(installed_db_ids == expected_db_ids, "smoke install: database membership differs")
        audit.note(
            "smoke install: correct folders; matching files replaced; "
            "new files added; unrelated files preserved"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit the complete Omega CCG installer release.")
    parser.add_argument("--no-smoke", action="store_true", help="Skip isolated payload extraction.")
    args = parser.parse_args()
    audit = Audit()

    try:
        cards = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
        active_ids = load_card_ids(CARDS_PATH)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cards source failed: {exc}") from exc
    monster_ids = {
        int(card["passcode"])
        for card in cards
        if str(card.get("category")) == "Monster"
    }
    audit.note(f"source: {len(active_ids)} unique active CCG card IDs")
    audit_source_metadata(audit, cards)

    try:
        script_paths = collect_scripts(SCRIPTS_DIR, active_ids)
        verify_archive(script_paths, SCRIPTS_ZIP_PATH)
        audit.note(
            f"scripts: {len(active_ids)} active and "
            f"{len(COMPATIBILITY_SCRIPT_IDS)} compatibility card scripts; "
            "no helpers/orphans"
        )
    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        audit.errors.append(f"scripts: {exc}")

    expected_db_ids = audit_database(audit, cards, active_ids)
    groups = {
        "Arts": archive_parts(DOWNLOADS, "YGO_Omega_Images_v"),
        "Pics": archive_parts(DOWNLOADS / "YGO_Omega_Images", "YGO_Omega_Pics_v"),
        "Holograms": archive_parts(DOWNLOADS / "YGO_Omega_Images", "YGO_Omega_Holograms_v"),
    }
    audit_image_group(audit, "Arts", groups["Arts"], "YGO_Omega_Images_v", "jpg", active_ids)
    audit_image_group(audit, "Pics", groups["Pics"], "YGO_Omega_Pics_v", "jpg", active_ids)
    audit_image_group(
        audit,
        "Holograms",
        groups["Holograms"],
        "YGO_Omega_Holograms_v",
        "png",
        monster_ids,
    )
    audit_holograms_from_arts(
        audit,
        groups["Arts"],
        groups["Holograms"],
        monster_ids,
    )
    audit.require(BANLIST_PATH.is_file() and BANLIST_PATH.stat().st_size > 0, "banlist: payload is missing/empty")
    audit_installer_constants(audit, groups)
    audit_website_downloads(audit, groups)

    if not args.no_smoke and not audit.errors:
        smoke_extract(audit, active_ids, monster_ids, expected_db_ids, groups)

    for note in audit.notes:
        print(f"PASS  {note}")
    if audit.errors:
        for error in audit.errors:
            print(f"FAIL  {error}")
        print(f"\nOmega release audit failed with {len(audit.errors)} error(s).")
        return 1
    print("\nOmega release audit passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
